### ISSUE TITLE
Updates to watched vault secrets don't restart the process

### ISSUE THREAD

**Issue by ShaneDrury** [hashicorp/envconsul#101]
When watching a vault secret and the secret is updated, the change is not picked up by envconsul.

Steps to reproduce:
  1. `vault server -dev`
  2. In another terminal: `VAULT_ADDR='http://127.0.0.1:8200' vault write secret/passwords foo=bar`
  3. `VAULT_ADDR='http://127.0.0.1:8200' VAULT_TOKEN={TOKEN} envconsul -pristine -secret secret/passwords python -c 'import os, time, logging; logging.error(os.environ); time.sleep(1000);'`
  4. In another terminal: `VAULT_ADDR='http://127.0.0.1:8200' vault write secret/passwords foo=baz`
  5. Note that the other process is not restarted

Using consul as the backend *does* work and the process is restarted correctly. Running Vault in non-dev mode also does not work.

Any help would be appreciated.
Version info:
```bash
$ vault --version
Vault v0.5.2
```
```bash
$ envconsul --version
envconsul v0.6.1
```

**Comment by sethvargo** [comment]
Hi @ShaneDrury 

Thank you for opening an issue. This is the intended behavior, because Vault does not support blocking queries at this time.

**Comment by ShaneDrury** [comment]
Ah, that's a shame. Thank you for the quick reply though.

**Comment by jdotjdot** [comment]
@sethvargo We're currently using Vault to manage both secrets and env vars--what is the right way to get the application to auto restart if a secret is changed?  And from this it sounds like we should store our secrets in Vault but the rest of the configuration variables in consul?  We were just hoping not to have to stand up another service and just do it all with Vault.
