### ISSUE TITLE
Implement -ignore-error flag to allow envconsul to operate when consul is unavailable

### ISSUE THREAD

**Issue by mwicat** [hashicorp/envconsul#105]
As @armon  said in https://github.com/hashicorp/envconsul/issues/42#issuecomment-88293206 :
> I think it makes sense for envconsul to handle the case of Consul failing after it starts, and continue to use the old values until Consul recovers / restarts. But it seems strange to start without any values on error. I think that would be a very surprising behavior for most users.

We are testing envconsul with uwsgi running under it. In our setup settings from consul are mainly used to override hardcoded settings in runtime so we can live without filling them by envconsul (also I suppose it is not quite uncommon for other users to have default like ``os.getenv('MYSETTING', 'MYDEFAULT')``

What we cannot live with is possibility that uwsgi won't start when consul is unavailable e.g. after restart. Adding flag that allow envconsul to start children in case consul is not available (and of course envconsul should check periodically if consul is available again) would make possible that even if service needs the setting for some features, that features will fail but the rest of the service will work.

**Comment by sethvargo** [comment]
Hi @mwicat 

I just tested this, and I think the behavior Armon described is the behavior that envconsul currently exhibits. Envconsul will not start the child process if it cannot connect to Consul. As Armon said, "it seems strange to start without any values on error. I think that would be a very surprising behavior for most users.".

If envconsul loses connection to the Consul cluster after it's fetched initial values, it happily retries in the background and manages the child processes.

I understand your use case, but I do not think it is in line with the project goals. Thank you for understanding! 😄
