### ISSUE TITLE
download removed?

### ISSUE THREAD

**Issue by bcyang** [hashicorp/envconsul#108]
https://github.com/hashicorp/envconsul/releases/download/v0.6.0/envconsul_0.6.0_linux_amd64.zip
is no longer there?

**Comment by sethvargo** [comment]
Hi @bcyang 

The downloads have been moved to the HashiCorp releases service. When we announced releases service, we said that new downloads will be published there and we will remove the github downloads in the future. Please use releases.hashicorp.com. Thanks and sorry!
