### ISSUE TITLE
Unexpected response code: 504

### ISSUE THREAD

**Issue by aabed** [hashicorp/envconsul#109]
**My setup**

consul ====> nginx ====> Internet

**What happens**
Nginx times out before consul replies to it, causing error 504 to be sent to envconsul, which seems to be unhandled and causes the child process to be dead

**Expected**
envconsul handles the 504 error and retry

**Work around**
Increase the timeout times on Nginx

**Comment by jippi** [comment]
they use long-polling / blocking connections for listening for changes, so they will wait forever for a new update, so i guess this is expected behavior :) fix is to increase timeout in nginx indeed

**Comment by aabed** [comment]
Cool, thanks
