### ISSUE TITLE
passing environment variable to a docker run

### ISSUE THREAD

**Issue by girishramnani** [hashicorp/envconsul#114]
i am trying to pass environment variable from consul to docker.
```envconsul -consul 127.0.0.1:8500 -prefix dev/ docker run -e PORT=$PORT```
and the `$PORT` env variable is present as a key and in can even see it using the `envconsul env` but its not passed to docker in this scenerio.

**Comment by sethvargo** [comment]
@girishramnani 

That's likely because your shell is interpolating that value before sending it to envconsul. Try:

```
envconsul -consul 127.0.0.1:8500 -prefix dev/ 'docker run -e PORT=$PORT'
```

**Comment by girishramnani** [comment]
the way `exec.Command` works is that it will show `docker run -e PORT=$PORT` doesnt exists in the $PATH

**Comment by girishramnani** [comment]
so i solved this by doing
```/bin/sh -c "envconsul -consul 127.0.0.1:8500 -prefix dev/ 'docker run -e PORT=$PORT'"```

**Comment by liviuignat** [comment]
Hi guys, I've been having also some problems with this. Ive tried several approaches and none worked. I also tried what you guys described here and did not work, like:

1. `envconsul --config /path/to/conf.hcl -pristine -prefix express-es6 docker run -d -p 8100:8100 --name express-es6 docker-repository.org/express-es6` - no variables copied to the container

2. `envconsul --config /path/to/conf.hcl -pristine -prefix express-es6 'docker run -d -p 8100:8100 --name express-es6 docker-repository.org/express-es6'` - throws the error `[ERR] fork/exec docker run -d -p 8100:8100 ....`

Any suggestions would be greatly appreciated. 
Liviu

**Comment by girishramnani** [comment]
you can do something like this 
```
./envconsul -consul 127.0.0.1:8500 -pristine -log-level info -prefix express-es6 /bin/bash -c  'docker run -e PORT=$PORT alpine env' 
```
here the bash will become the child process of env consul and hence it has access to all the env variables.
so basically you can try and pass the env variables inline
```
envconsul --config /path/to/conf.hcl -pristine -prefix express-es6 /bin/bash -c 'docker run -d -e PORT=$PORT  -p 8100:8100 --name express-es6 docker-repository.org/express-es6' 
```
