### ISSUE TITLE
Watching folders

### ISSUE THREAD

**Issue by wheelybird** [hashicorp/envconsul#115]
Hello.  Is it not possible to watch folders when using Vault?  I get ` missing data for "secret(secret/folder)" when trying to do so (specifying a single key works fine).

There also seems to be an issue with watching normal consul folders - adding a key will cause envconsul to trigger a reload, but it doesn't seem to return the key just added.  It will show up on the next modification, but that means you'd need to add a key and then modify it for it to be passed on by envconsul.

**Comment by jefferai** [comment]
Vault doesn't have an eventing system so without polling it's not possible to watch folders, and I don't think `envconsul` supports polling.

**Comment by wheelybird** [comment]
Ah, cheers for that.  That would explain why.

**Comment by wheelybird** [comment]
Incidentally, any ideas on the second issue - a new key not showing up when envconsul reloads a service?

**Comment by sethvargo** [comment]
Hi @wheelybird 

Can you please share your complete command and the output in debug mode.

**Comment by sethvargo** [comment]
Hi there,

I am going to close this due to a lack of response. If this is still occurring, please open a new issue. Thanks! 😄
