### ISSUE TITLE
bug: envconsul does not die when child process exit

### ISSUE THREAD

**Issue by jippi** [hashicorp/envconsul#117]
Currently when the process started by envconsul dies, the envconsul program keep running, letting the child program staying dead.. this is quite a problem when running programs under `supervsiord`

example:

```
/usr/local/bin/envconsul -config /etc/envconsul/config.hcl -prefix apps/production/env -prefix apps/production/supervisor/unsubcribe_server/env -sanitize -upcase Console/cake users unsubcribe_server
```

when the `Console/cake users unsubcribe_server` program dies, `envconsul` keep running, and thus supervisor will never restart the actual process :( 

Using `-once` works, but then envconsul won't restart the process when relevant consul keys change

The exit behavior of `-once` with the `envconsul` dieing like the child process would be the expected behavior for me :)

version: v0.6.1

**update**

```
envconsul -prefix apps/production/env -config /etc/envconsul/config.hcl -pristine -sanitize /bin/ping 8.8.8.8` and then `killall ping` do seem to kill `envconsul
```
I've observed that *sometimes* in my production environment this does not happen, the children process dies, but `envconsul` never terminates - especially when an exception is throw in my php code

**Comment by sethvargo** [comment]
HI @jippi 

I can't reproduce this, and there are tests that cover this. Are you sure you aren't spawning a process that spawns a child? Can you inspect the process with `ps auxw` or `pstree`?

As a quick example, just run:

```envconsul -prefix=whatever env```

When `env` exits, so to does envconsul. I'm willing to bet that `cake` (not familiar) is spawning a child process which it then does not monitor.

**Comment by jippi** [comment]
@sethvargo it seem to be something happening once in awhile, the same `cake` (cakephp app) works when i just test locally, even 1000 tests.. but once in awhile i observe it in production, after the script has been running for days and then dies.. the last message in the output is similar to `Program exited, code 127` - I'll find an exact message next time it happens :) 

again, 99,999% of the time, everything works as it should.. though sometimes.. not :(

**Comment by sethvargo** [comment]
Hey @jippi 

Without a reproduction case or debug logs, I'm afraid there's nothing we can do. I cannot reproduce this in my testing of a massive bash loop.

Can you try running Envconsul in debug mode and grabbing the output when this happens again?
