### ISSUE TITLE
Leader Election?

### ISSUE THREAD

**Issue by n2taylor** [hashicorp/envconsul#119]
Any plans to add support to `envconsul` for leader election in the style of https://www.consul.io/docs/guides/leader-election.html? Meaning, don't run the child process unless it has acquired leadership on a specified key.

e.g.
```
envconsul \
    -consul 127.0.0.1:8500 \
    -prefix app/config \
    -elect-leader app/leader-key \
    my_child_process
```

**Comment by sethvargo** [comment]
Hi @n2taylor 

There are no plans to do this. You can easily implement client-side leader election by wrapping the envconsul command in a consul lock command. Thanks and have a great day!
