### ISSUE TITLE
Don't expose token in error messages

### ISSUE THREAD

**Issue by aseppala** [hashicorp/envconsul#120]
Now when envconsul is logging error messages such as

```
2016/11/22 13:20:59 [ERR] (view) "storeKeyPrefix(/foo/bar)" store key prefix: error fetching: Get http://consul:8500/v1/kv/foo/bar?index=302705&recurse=&stale=&token=<token>&wait=60000ms: dial tcp: lookup consul 8.8.8.8:53: no such host
```

or

```
2016/11/22 13:20:59 [ERR] (runner) watcher reported error: store key prefix: error fetching ...
```

it exposes the consul token. It would be good to sanitise the actual value of the token from the log messages.

**Comment by sethvargo** [comment]
Hi @aseppala 

That error is actually coming from go's net/http library - that is the URL that is being requested. /cc @slackpad could we use a header here?

**Comment by slackpad** [comment]
Yep - if you pull in the latest version of the Consul client API library it will always use a header for the token. Just a vendor update should do it.

**Comment by sethvargo** [comment]
Sweet. Good to know and easy fix

**Comment by aseppala** [comment]
Nice, thanks for taking care of this!
