### ISSUE TITLE
Allow adding a prefix to env variable names

### ISSUE THREAD

**Issue by smunch** [hashicorp/envconsul#121]
It would be helpful to be able to specify a prefix to be added to environment variable names created by a run of envconsul. This would allow a little more customization at execution time to help prevent possible env var name collisions without having to clutter up key naming in the kv store.

I'm thinking something like:
`envconsul -keyprefix=CONSUL_ ...`

to generate env vars from consul keys such as
`CONSUL_foo=123`
`CONSUL_bar=abc`

where keys were named foo, bar in the kv store.

It could be this functionality exists and I've just missed it somehow

**Comment by sethvargo** [comment]
Thank you for the PR. This is interesting, but I'd like to hear a bit more information. We currently have a "format" configurable on a per-key basis that allows really deep customization. Would that work in this situation?

```hcl
prefix {
  key = "foo"
  format = "MY_PREFIX_{{ key }}"
}
```
