### ISSUE TITLE
Problems with args with spaces

### ISSUE THREAD

**Issue by nhocki** [hashicorp/envconsul#123]
(`envconsul` version is `v0.6.1`)

Hello,

It seems that `envconsul` messes up params sent to executables when they're
quoted.

I've confirmed this with the following Go program:

```go
package main

import (
	"fmt"
	"os"
)

func main() {
	fmt.Printf("Total args: %d\n", len(os.Args))
	fmt.Printf("Args: %q\n", os.Args)
}
```

If I run it without `envconsul` I get this:

```
$ ./main 'first arg' 'second arg'
Total args: 3
Args: ["./main" "first arg" "second arg"]
```

But if I run it with envconsul, the single quotes are ignored and I get more arguments:

```
$ envconsul --prefix=app ./main 'first arg' 'second arg'
Total args: 5
Args: ["/data/tmp/nh-go-cli-test" "first" "arg" "second" "arg"]
```

Here's the output with `log-leven=info`:

```
$ envconsul --log-level=info --prefix=app ./main 'first arg' 'second arg'
2017/01/05 21:30:04 [INFO] envconsul v0.6.1
2017/01/05 21:30:04 [INFO] (runner) creating new runner (command: [./main first arg second arg], once: true)
2017/01/05 21:30:04 [INFO] (clients) creating consul/api client
2017/01/05 21:30:04 [INFO] (clients) creating vault/api client
2017/01/05 21:30:04 [INFO] (runner) creating Watcher
2017/01/05 21:30:04 [INFO] (runner) starting
2017/01/05 21:30:04 [INFO] (watcher) adding "storeKeyPrefix(app)"
2017/01/05 21:30:04 [INFO] (view) "storeKeyPrefix(app)" received data
2017/01/05 21:30:04 [INFO] (runner) running
2017/01/05 21:30:04 [INFO] (runner) running command ./main first arg second arg
Total args: 5
Args: ["./main" "first" "arg" "second" "arg"]
2017/01/05 21:30:04 [INFO] (runner) running
2017/01/05 21:30:04 [INFO] (cli) subprocess exited
2017/01/05 21:30:04 [INFO] (runner) environment was the same
2017/01/05 21:30:04 [INFO] (runner) stopping
2017/01/05 21:30:04 [INFO] (watcher) stopping all views
```

I'm not really sure if this is a bug or I'm missing something. I can't find how
to make it work. I've tried the following with no luck:

```
$ envconsul --prefix=app "/data/tmp/nh-go-cli-test 'first arg' 'second arg'"

$ envconsul --prefix=app '/data/tmp/nh-go-cli-test "first arg" "second arg"'

$ envconsul --prefix=app /data/tmp/nh-go-cli-test 'first\ arg' 'second\ arg'
```

Any idea on how to make this work?

Thanks!

**Comment by c4milo** [comment]
I made it work escaping the single quotes.

### t.go
```go
package main

import "fmt"
import "os"

func main() {
	exec(os.Args[1:]...)
}

func exec(args ...string) {
	fmt.Println(args)

	for _, e := range os.Environ() {
		fmt.Println(e)
	}

}
```

### Loading something in Consul

```
$ consul kv put config/redis/maxconns 5
Success! Data written to: config/redis/maxconns
```

### Running envconsul
Notice the single quotes being escaped 

```
$ envconsul -pristine -upcase --prefix=config/redis go run t.go blah \'eso mijo\'
[blah 'eso mijo']
MAXCONNS=5
````

**Comment by nhocki** [comment]
@c4milo I still can't get it to work and I have no idea why 💔  ... Here's a simpler example:

```
$ envconsul --version
envconsul v0.6.1


$ cat consul_help 
#!/bin/sh
echo "Args: $1 ** $2"


$ envconsul --prefix=app -consul=demo.consul.io sh consul_help foo 'bar baz'
Args: foo ** bar


$ envconsul --prefix=app -consul=demo.consul.io sh consul_help foo \'bar baz\'
Args: foo ** 'bar

```

**Comment by sethvargo** [comment]
Hi all,

I'm having trouble reproducing this at all off of master. Here is a tiny Ruby script:

```ruby
#!/usr/bin/env ruby

puts ARGV.size
puts ARGV.inspect
```

```shell
$ ENVCONSUL_LOG=debug envconsul -prefix=foo ~/Desktop/test/x.rb 'foo bar' 'baz bit'
# ...
2017/01/13 16:58:20 [INFO] (runner) running command /Users/sethvargo/Desktop/test/x.rb foo bar baz bit
2
["foo bar", "baz bit"]
```

Could you please try master and see if this is occurring? Do you see anything wrong with my script?

**Comment by nhocki** [comment]
@sethvargo Hey! First of all thanks for looking into this. I found out that the problem we're having was only happening on our servers (and not locally, for example). After digging deeper into our Ansible roles, I found the problem and it's 100% on our end.

We're downloading `envconsul` to `/opt/envconsul` and then we add a wrapper around it (I have no idea why!) which pretty much does this (in `/usr/local/bin/envconsul`):

```sh
#!/bin/bash

opt/envconsul $@
```

That `$@` will mess everything up! If we use `/opt/envconsul` directly everything works as expected.

If we had had the wrapper be the following, it would have worked:

```sh
#!/bin/bash

opt/envconsul "$@"
```

Thanks again for looking into this and sorry it was all on our side!
