### ISSUE TITLE
Read ~/.vault-token if it exists

### ISSUE THREAD

**Issue by domg123** [hashicorp/envconsul#139]
Similar to [consul-template](https://github.com/hashicorp/consul-template/pull/878) and [terraform](https://github.com/hashicorp/terraform/pull/11529).  If VAULT_TOKEN is unspecified in the environment or config, try to use the vault token file, if present.

**Comment by alinoeabrassart** [comment]
This would be great, we use this file too to rotate the vault tokens

**Comment by jantman** [comment]
It would be even better if the path could be configurable somehow, just defaulting to ``~/.vault-token``.

**Comment by sethvargo** [comment]
This is fixed on master by upgrading the underlying client API. No other tools provide a customizable VAULT_TOKEN_PATH, so we opted to not include that.
