### ISSUE TITLE
[Question] How Splay Works

### ISSUE THREAD

**Issue by vrenjith** [hashicorp/envconsul#140]
As per the docs:
> splay	The maximum time to wait before restarting the program, from which a random value is chosen.

So let's also assume that we have set 30s as the `splay` duration. I have two questions:
* Does this mean that the `kill_signal` will be sent after anywhere between `0` and `30` seconds?
* If we specify `SIGUSR1` as the signal will `envconsul` still send a `SIGTERM` after the `splay` duration? Or to put in other words, what will happen if the application decides to handle the signal and decide internally not to restart?

**Comment by sethvargo** [comment]
Hi @vrenjith 

Given a `splay` of 30s, each Consul Template process will independently choose a sleep time between 0 and 29999999999 nanoseconds (0-29.99999999s). After sleeping for that amount of time, it sends the configured signal to the process.

After 5s (default `kill_timeout`, configurable as `timeout`), if the process has still not exited, it will be sent SIGKILL (effectively `kill -9`).

There is no way to "replace" a running process' environment, so we have to stop and restart the task. If you application chooses to ignore the signal and not exit, it will be force-killed and started again.

**Comment by vrenjith** [comment]
Thank you for the clarification @sethvargo
