### ISSUE TITLE
on configs change in consul,envconsul exits along with the child process 

### ISSUE THREAD

**Issue by sdinakar85** [hashicorp/envconsul#143]
### Envconsul version
envconsul v0.6.2 (ddf8503)

### Configuration
location : /tmp/envconsul.hcl
```
prefix {
  path = "config/global"
}
consul    = "consul.service:8500"
```

### Command
```
envconsul -config=/tmp/envconsul.hcl /bin/sh -c /opt/startjava.sh 
```
/opt/startjava.sh (this is a simple start of java app)
```
java ${JMX_OPTS} ${JAVA_OPTS} -Xmx${NOMAD_MEMORY_LIMIT}m -Djava.security.egd=file:/dev/./urandom -jar /app.jar
```

### Debug output
Exits with the below error
```
Error: JMX connector server communication error: service:jmx:rmi://ff9d3083ad27:56814
2017/07/03 11:53:54 [ERR] unexpected exit from subprocess (1)
```

### Expected behavior
Expectation is the actual `envconsul` behaviour where the envconsul sends a SIGTERM to its child process in this case (java) on change in consul and envconsul should not exit , rather restart the java process

### Actual behaviour
envconsul exits along with the child process when there is a config change in consul.

**Comment by sethvargo** [comment]
Hi @sdinakar85 

If the child process dies, envconsul also dies. This is so, if you were running envconsul under something like upstart or systemd, you could detect/restart/alert on failure.

Could you share the complete debug log? It's true that envconsul should send a signal to the child process on configuration change, but it's hard to see the behavior with just this one log line. You can run with `-log-level=debug` for more detailed output.

**Comment by sdinakar85** [comment]
Thanks for the response @sethvargo
Found that he shell script calling the java command was exiting with a Non-Zero return code which was causing `envconsul` to die. We fixed that by adding a `exec` in the shell script where the java command was being called.
