### ISSUE TITLE
vault configs/behaviour

### ISSUE THREAD

**Issue by sdinakar85** [hashicorp/envconsul#144]
### Envconsul version
envconsul v0.6.2 (ddf8503)

### Configuration
/tmp/envconsul.hcl
```
vault {
  address = "https://active.vault.service:8200"
  token   = "123456-0ABCDEF-4567"
  renew   = true
}

secret {
    no_prefix = true
    path   = "secret/2ef6193d575045b98098f98f4232dd3c"
    format = "secret_{{ key }}"
}
```

### Command
```
envconsul -config=/tmp/envconsul.hcl  /bin/sh -c /opt/startjava.sh

startjava.sh has a simple java command that starts a springboot app
```

### Debug output
2017/07/03 12:16:26.413249 [WARN] (view) vault.token: Put https://127.0.0.1:8200/v1/auth/token/renew-self: dial tcp 127.0.0.1:8200: getsockopt: connection refused (retry attempt 1 after "250ms")

### Expected behaviour
Watch for a secret under path  secret/2ef6193d575045b98098f98f4232dd3c reload the app on change in secrets and logs should be clean without any warnings

### Actual behaviour
When envconsul is watching for a secret in vault, though we specify the the VAULT_ADDR as `https://active.vault.service:8200` we still see the message `[WARN] (view) vault.token: Put https://127.0.0.1:8200/v1/auth/token/renew-self: dial tcp 127.0.0.1:8200: getsockopt: connection refused (retry attempt 1 after "250ms")`. We want to know the reason for this behaviour. If possible let us know what needs to be changed in the configs(if any) . Also, when I write a secret to path `secret/2ef6193d575045b98098f98f4232dd3c`(which is being watched and it is part of the configs mentioned above) using `vault write secret/2ef6193d575045b98098f98f4232dd3c foo=bar` I was expecting `envconsul` to restart the child process with the new secrets set as env variables. This behaviour does not seem to happen. Please let us know if the understanding is correct.

**Comment by sethvargo** [comment]
Hi @sdinakar85 

When you give envconsul a Vault token, it will try to renew that token unless specifically disabled. You can disable the behavior by specifying `-vault-renew=false`.

Additionally, Vault does not support blocking queries (there are lots of other issues about this). This means that, unlike Consul, a change in a Vault secret does not "fire" immediately. Instead, you must wait for the lease to expire or restart the envconsul process.

Please let mek now if you have any questions.

**Comment by sdinakar85** [comment]
Thank you @sethvargo for the response. I still have two questions:
* We do want the token to be renewed. The query was, why is `envconsul` attempting to connect to `127.0.0.1` when in the `config.hcl` we have provided `active.vault.service` as the vault address
* By lease duration I am assuming that it is the lease duration of the `vault` token, which in our case we get using an `approle` login. Is this understanding correct?

**Comment by aleksandrmironov** [comment]
@sdinakar85 according to your second question. When you create a secret you can specify its ttl. E.g `vault write staging/password value=itsasecret ttl=1m`.
 When you read the secret:
`vault read staging/password
Key             	Value
---             	-----
refresh_interval	1m0s
aaaa            	dfdfd
ttl             	1m
value           	itsasecret`

And **envconsul** will refresh secrets every time refresh_interval period.
