### ISSUE TITLE
vault lease renewal; lease_id is specified via the URL path and not in the POST body

### ISSUE THREAD

**Issue by pieterbreed** [hashicorp/envconsul#145]
- I don't think mysql itself has much to do with this bug, although to see the bug, the connection to mysql has to be re-created as mysql caches credentials in connections.
 - I have this in a docker-compose repository here https://github.com/pieterbreed/vault-workbench (the "bug" is fixed by giving a more permissive access to the renewal URL in vault ACL by adding a wildcard at the end of the renew path)

### Envconsul version
`0.6.2`

### Configuration
```hcl
vault {
  address = "$VAULT_ADDR"
  renew = true
}

secret {
  path = "mysql/creds/full"
  format = "MYSQL_DB_{{ key }}"
  no_prefix = true
}
```

### Command
```shell
envconsul -upcase \
          -config envconsul.config \
          -log-level debug \
          ./mysql_test.sh
```

### Debug output
https://gist.github.com/pieterbreed/df22ac5e83ed7948155081d835419cab

Please look for `HERE IS THE BUG`

### Expected behavior
 - With the default policies (as of vault v0.7.2 ('d28dd5a018294562dbc9a18c95554d52b5d12390')) envconsul should be able to work out of the box for this use-case. Instead, I had to add this policy to make it work:
 - envconsul should renew the lease by sending the lease_id in the body of the post instead of in the URL path (if I read the documentation for the default policies in vault correctly)

```hcl
path "sys/renew/mysql*" {
	capabilities = ["update"]
}
```

### Actual behavior
The secret lease was not being renewed. (The token was being renewed just fine.)

### Steps to reproduce
1. Create a mysql dynamic secret and give access to it for a non-root token
2. load it using envconsul and the config file shown above
3. connect to mysql using cli, in a loop, using the secret from the env variable
4. wait for the lease to expire
5. watch the world burn

**Comment by sethvargo** [comment]
This is fixed in master by upgrading the underlying API client.
