### ISSUE TITLE
Build instructions incomplete

### ISSUE THREAD

**Issue by Leonidas-from-XIV** [hashicorp/envconsul#149]
### Envconsul version

None

### Configuration
```hcl
```

### Command
```shell
make dev
```

### Debug output

[Output](https://gist.github.com/Leonidas-from-XIV/e4f6232a3c8d73fc41a2009e71b7c32b).

### Expected behavior

It should have created an `envconsul` binary.

### Actual behavior

It output a lot of error messages about missing packages and failed. I guess there is a command required to actually install the dependencies, but it is not documented and I don't have the necessary Go experience to know what to do.

### Steps to reproduce

1. clone this repository
2. `make dev` like described in the `README`

### References

None.

**Comment by sethvargo** [comment]
Hi @Leonidas-from-XIV 

- How did you install Go (the programming language)?
- What happens if you run `go install ./...` directly?

**Comment by Leonidas-from-XIV** [comment]
Hi @sethvargo, thanks for your quick response:

  * I've installed it via `brew install go` which has installed Go 1.9 for me
  * The error message is exactly the same.

I've managed to kinda compile that, by moving everything in `vendor` to `vendor/src`, symlinking the `version` folder into `vendor/github.com/hashicorp/envconsul/version`, creating a `bin` folder and running

```sh
env GOPATH=$(pwd)/vendor GOBIN=$(pwd)/bin make dev
```

And it did generate an `envconsul-0.7.2` binary in the `bin` folder, but I suspect that this is most likely not the way to do it properly.

**Comment by sethvargo** [comment]
Oh oh. Where did you clone into? You have to clone into `$GOPATH/github.com/hashicorp/consul-template`

**Comment by Leonidas-from-XIV** [comment]
I don't have a `$GOPATH` set, usually. I've just cloned `envconsul` into `$HOME` and tried to build.

**Comment by sethvargo** [comment]
Hi @Leonidas-from-XIV 

You have to have a $GOPATH set to do go development.

**Comment by Leonidas-from-XIV** [comment]
Hi @sethvargo. I don't want to do Go development. `envconsul` is an application useful for end-users (or well, developer end-users), so I just want to compile it to package it for homebrew: https://github.com/Homebrew/homebrew-core/pull/17442

**Comment by jippi** [comment]
Why not download from https://releases.hashicorp.com/envconsul/ ?

**Comment by Leonidas-from-XIV** [comment]
@jippi Because homebrew [does not accept binary-only packages](https://docs.brew.sh/Acceptable-Formulae.html). Same with e.g. Debian and most likely other GNU/Linux distributions.

I think it makes sense, because if there is some thing that needs to be patched, it can be done if the package can be built from source instead of having to raise the issue at upstream and hope they will release an updated binary soon.

**Comment by jefferai** [comment]
@Leonidas-from-XIV If you are compiling a Go package, you are de facto doing Go development, and as such you *must* follow the rules for compilation that Go requires, including using a GOPATH. See https://golang.org/doc/code.html

**Comment by Leonidas-from-XIV** [comment]
I'm just asking for the build instructions to be extended so I don't have to learn how to do Go development just to get a binary.

If it is "set `$GOPATH` to XYZ, run `make dev`, here's your binary" I'm perfectly happy.

**Comment by jippi** [comment]
@Leonidas-from-XIV maybe push it out as a Homebrew Cask instead - thats all binary releases

**Comment by Leonidas-from-XIV** [comment]
@jippi That still has the issue that if there is something to be patched that it is impossible. Say, for example a new Go release. Or some security vulnerability. I specifically went out to package this tool for homebrew so I don't have to depend on a binary that apparently is quite difficult to reproduce.

**Comment by jefferai** [comment]
@Leonidas-from-XIV You are essentially stating that any project using any language should include instructions for installing and configuring that language. But the language and a project using that language are entirely separate items. And by extension, in case anyone might want to build a .deb for a package, every project should include complete instructions for installing Debian build tools and running a build. Same for Ubuntu with launchpad PPAs; also for Arch, Red Hat, and so on.

I appreciate that you are not familiar with Go, but there are very complete instructions available on setting up a Go development environment, including what I linked you to earlier. We're simply not going to add instructions on installing and configuring your Go environment to the readme of this project.

**Comment by sethvargo** [comment]
I also just went through this argument with another homebrew maintainer for consul-template (a similar tool): https://github.com/hashicorp/consul-template/issues/999. We provide compressed, tested, and signed binaries for consumption. When you compile from source, you throw many of those processes out the window.

**Comment by Leonidas-from-XIV** [comment]
Since this issue is closed I don't plan to spend more time on this, but since there is still discussion: 

> You are essentially stating that any project using any language should include instructions for installing and configuring that language.

But `envconsul` is not a language. And yes, in fact I do expect from an instruction to build a program to know how to build a program after reading it. It would be different if `envconsul` were a library, then I would not complain, since then it is clearly geared towards Go developers.

> by extension, in case anyone might want to build a .deb for a package, every project should include complete instructions for installing Debian build tools and running a build.

That's absolutely not what I am saying, I didn't ask how to build a Debian package or a Homebrew package or whatever. I'm just wondering how to get a `envconsul` binary, without needing to dive into how to build programs with Go. C projects often state `./configure && make && make install` without me having to know how to build C libraries.

@sethvargo I appreciate your thoughts on it, it is a long discussion and it might be helpful for my packaging. I disagree on your points though, since the fact that it is signed does only mean that I need to trust the person signing it. The fact that they are tested is quite mysterious to me, since I am surprised what kind of testing you are doing that could not be done as part of the build process on e.g. my own machine. Why is there concern about the binaries that I build myself?

Thanks to a friend I managed to build it now:

 1. create empty folder, e.g. `/tmp/gobuild`
 2. create an `src/github.com/hashicorp/envconsul` subfolder inside with the contents of this git repo (I think this was what @sethvargo meant, but I misunderstood him)
 3. Change to that subfolder and run `GOPATH=/tmp/gobuild make dev`
 4. Find the binary in `/tmp/gobuild/bin/envconsul`

I am not sure why you are so opposed to add something short like this to the README. I was thinking of making a PR but it doesn't seem like there is much interest in this. Your project, your rules, have a nice evening and goodbye! 👋
