### ISSUE TITLE
Feature request: allow for missing or optional secrets

### ISSUE THREAD

**Issue by bloo** [hashicorp/envconsul#150]
### Envconsul version

0.7.1

### Configuration
```hcl
upcase = true
vault {
  address = "${VAULT_ADDRESS}"
  token = "${VAULT_TOKEN}"
}
secret {
  path = "secret/clusters/defaults"
  no_prefix = true
}
secret {
  path = "secret/clusters/${CLUSTER_NAME}"
  no_prefix = true
}
```

### Request

We'd like to make some secrets optional so that envconsul doesn't fail if, for example, we have no `defaults` and don't want to have an empty secret object in vault.

Suggested implementations:

```hcl
secret {
  path = "secret/clusters/defaults"
  no_prefix = true
  optional = true
}
```

or 

```hcl
secret {
  path = "secret/clusters/defaults"
  no_prefix = true
  required = false
}
```

Thanks!

**Comment by sethvargo** [comment]
Hi @bloo 

This is closely related to https://github.com/hashicorp/consul-template/issues/165. In short, Vault considers 404's errors, and there's no way to differentiate between "404 doesn't exist" and "404 you don't have access". We also actively recommend against this "inheritance-style" approach to secrets management. Instead you should have a separate process that replicates your "defaults" into secret/clusters/CLUSTER_NAME and just read that secret directly.

**Comment by bloo** [comment]
@sethvargo thanks for the input!
