### ISSUE TITLE
Question: How to handle token renewal in Vault EC2/IAM Auth Client Nonce case?

### ISSUE THREAD

**Issue by boldandbusted** [hashicorp/envconsul#172]
Howdy. I hope this is proper to ask usage questions here, but not sure where the better place would be. I'm implimenting Vault, and configuring the use of the Vault AWS backend to accomplish the deep magic of the EC2/IAM Client Nonce-derived token. How do I properly handle token renewal when using envconsul? Is that something I should handle outside envconsul (until there's internal support for this particularly tricky auth scenario)? Thanks! :)

P.S. If this is the wrong place to post questions, cluebat is welcomed. ;)

**Comment by eikenb** [comment]
Hey @boldandbusted, sorry for the long delay in a response.

Probably much to late, but just in case (and for the future) I believe the best place to ask questions like this would be in the consul mailing list.

https://groups.google.com/group/consul-tool

I made a note to myself to add a mention in the Readme about community resources.
Thanks.
