### ISSUE TITLE
Reload signals to child process

### ISSUE THREAD

**Issue by jmjolysc** [hashicorp/envconsul#182]
Currently Envconsul does not send reload signals to child processes. Would proxying reload signals be supported in the future? In my use case I wouldn't mind a SIGHUP triggering both the envconsul and child process reloads if it were available as an option.

**Comment by anhldbk** [comment]
Still I don't know how to reload child processes when configurations are changed. @jmjolysc Have you got any idea?

**Comment by jmjolysc** [comment]
@anhldbk That's the problem with envconsul (at least when I tested it a few months ago). The SIGHUP signal is caught by enconsul so that it's able to update the environment variables. But the child process doesn't receive any reload signal, so it has no way to refresh its own state from the updated envars.

**Comment by anhldbk** [comment]
@jmjolysc I've found another solution using `consul-template`. To me, `consul-template` is a wrapper for `envconsul`.

**Comment by jmjolysc** [comment]
Cool, thanks for that!
