### ISSUE TITLE
Feature: Env processing in hcl

### ISSUE THREAD

**Issue by jhmartin** [hashicorp/envconsul#191]
It would be useful to be able to specify environmental variables in config.hcl:

```
secret {
  format = "DB_{{ key }}"
  path      = "{{.VAULT_DB_ROLE}}"
}
```

As this environment is configured via Terraform such that the vault path changes based on the deployment; however the format option is very convenient for exposing variable w/known names to later scripts, without falling back to the overly generic USERNAME/PASSWORD values.

There doesn't seem to be a way to specify this on the command line.

envconsul v0.7.3 (daa2947)

**Comment by tyd** [comment]
See https://github.com/hashicorp/envconsul/pull/167 ...hopefully they can merge that with a few other items soon!

**Comment by jhmartin** [comment]
I see it now, closing in favor of that.
