### ISSUE TITLE
vault renewer custom increment

### ISSUE THREAD

**Issue by fussybeaver** [hashicorp/envconsul#196]
### Envconsul version
envconsul v0.7.3 (daa2947)

### Configuration
```sanitize = true
upcase = true
wait = "2s:8s"
reload_signal = "SIGTERM"

secret {
  no_prefix = true
  path = "postgres/creds/redacted"
}

vault {
  address = "http://vault.service.consul"
  renew_token = true
  grace = "3600s"
}
```

### Command
Create a token called "a_token" and call envconsul
```shell
curl -i --request POST -H 'Content-Type: application/json' -H 'X-Vault-Token: myroot' -d '{"id":"a_token","renewable":"true","ttl":"2m","policies":["redacted"]}' https://vault.redacted.com/v1/auth/token/create
VAULT_TOKEN=a_token /usr/bin/envconsul -exec-kill-signal=SIGTERM -exec-kill-timeout=60s -consul-addr=10.10.10.10:8500 -config /etc/envconsul-config.hcl -prefix redacted/config env
```

### Debug output
https://gist.github.com/fussybeaver/cfdcdc1db083b18f2358276e4149789c

### Expected behavior
Token renewed with expected TTL

### Actual behavior
Using `strace` we discovered that envconsul was doing a PUT to the `auth/token/renew-self` (as opposed to a POST as documented [here](https://www.vaultproject.io/api/auth/token/index.html#renew-a-token-self-)). Vault would respond with (note the increment zero):

```
{\"request_id\":\"a5500f1f-87d0-3e75-45f9-60014553a5e9\",\"lease_id\":\"\",\"renewable\":false,\"lease_duration\":0,\"data\":null,\"wrap_info\":null,\"warnings\":null,\"auth\":{\"client_token\":\"a_token\",\"accessor\":\"7b0b1914-d516-9b37-7cd7-74d9eab50331\",\"policies\":[\"default\",\"redacted\"],\"token_policies\":[\"default\",\"redacted\"],\"metadata\":null,\"lease"...
```

This was then followed by errors such as the following, and the token immediately expiring:
```
[WARN] vault.token: renewer returned (maybe the lease expired)
[WARN] (view) lease expired or is not renewable (retry attempt 1 after \"250ms\")
```

Surprisingly, we concluded that an increment of zero actually sets the lease to expired.

### Steps to reproduce
1. Create a vault token with access to a policy, setting `renewable` and a TTL.
2. Call the `renew-self` API 

### References
We discovered this is caused by a previous issue in vault:
 - https://github.com/hashicorp/vault/issues/3870

Which was fixed by:
 - https://github.com/hashicorp/vault/pull/3904

**Comment by sgerrand** [comment]
👋 @catsby @pearkes @kyhavlov: Would you please review this change.

**Comment by eikenb** [comment]
I'm only able to partially reproduce this. Using the existing vendored dependencies, following the notes above I create a renewable token with a TTL. I then run the envconsul command and see the mentioned output...

    [WARN] vault.token: renewer returned (maybe the lease expired)
    [WARN] (view) lease expired or is not renewable (retry attempt 1 after "250ms")

But checking the token status with `vault token lookup` shows the TTL has being refreshed and renewable as true. As long as run the envconsul command within the TTL it seems to work even though it spits out the warning.

If I rebuild using updated dependencies/newer versions the WARN does go away and everything still works.

I am using vault 1.1.2, so maybe something was changed there that helped.

I'm still going to update the dependencies in case I'm just missing something.
