### ISSUE TITLE
Docker Hub image out of date

### ISSUE THREAD

**Issue by nvllsvm** [hashicorp/envconsul#199]
The [`hashicorp/envconsul`](https://hub.docker.com/r/hashicorp/envconsul) image on Docker Hub is out of date. Only version 0.7.0 is available - versions 0.7.1 and onward are missing.

https://hub.docker.com/r/hashicorp/envconsul

![image](https://user-images.githubusercontent.com/6550543/55033670-0d901a00-4fea-11e9-89c6-f0fa741c73d2.png)

```
$ docker pull hashicorp/envconsul
$ docker run --rm hashicorp/envconsul --version
envconsul v0.7.0 (0bc402e)
```

```
$ docker pull hashicorp/envconsul:alpine
$ docker run --rm hashicorp/envconsul --version
envconsul v0.7.0 (0bc402e)
```

**Comment by eikenb** [comment]
I am making this part of the 0.8 milestone, but it will happen after the 0.8 release (and I'll push the 0.8 version).

**Comment by eikenb** [comment]
This is the last outstanding issue before the release. Trying to see if I can get the image build automated as part of the release. If not I'll roll it by hand and upload it.

**Comment by eikenb** [comment]
Just pushed 8.0 Docker images.
