### ISSUE TITLE
Update alpine based docker image

### ISSUE THREAD

**Issue by eikenb** [hashicorp/envconsul#229]
Eliminate use of old internal docker-base "package".
Remove any unused alpine packages (possible candidates; curl, libcap, openssl).
Any other cleanup/improvements.

This corresponds with a similar consul-template issue (they use the same basic Dockerfile). https://github.com/hashicorp/consul-template/issues/1245

**Comment by eikenb** [comment]
Converted to a bug as that old docker-base "package" is going away. After that we won't be able to build an envconsul docker image until this is fixed.

**Comment by maxim-nazarenko** [comment]
@eikenb I would like to take care of this.

what are your thoughts: may I start working on this issue before merge of #230?

**Comment by eikenb** [comment]
Hey @maxim-nazarenko, thanks for jumping in. Please have a go at it. There's no required ordering here and getting this fixed will be a big help. Thanks!

**Comment by eikenb** [comment]
@maxim-nazarenko .. Still catching up from the holiday break and I see why you mentioned #230, you already submitted a PR for it. I'll try to give that a look tomorrow to keep the ball rolling.
