### ISSUE TITLE
alpine docker image shouldn't run entrypoint as root

### ISSUE THREAD

**Issue by eikenb** [hashicorp/envconsul#230]
Envconsul's Alpine docker image was cut-n-pasted over from consul-template. In https://github.com/hashicorp/consul-template/pull/1324 the Alpine docker image was reworked to eliminate running as root. 

This should be done here as well and the risk of a breaking change doesn't impact envconsul as it doesn't generate files that could be written to the mounted volume, like is possible with consul-template.

**Comment by maxim-nazarenko** [comment]
hey @eikenb, 
may I adapt your approach in the mentioned PR and use it here?

**Comment by eikenb** [comment]
Hey @maxim-nazarenko ... Please do and thanks!
