### ISSUE TITLE
Customize envvar name for dynamic credentials

### ISSUE THREAD

**Issue by niclarcipretti** [hashicorp/envconsul#234]
Hi,

I was wondering if I can customize the envvars names when using dynamic credentials generated by database secret engine, once the default way of doing this stucks me with "username"/"password" keywords?

Eg.

```
secret {
  ...
  format="MY_ENV_{{ key }}"
}
```

generates:

```
MY_ENV_USERNAME=foo
MY_ENV_PASSWORD=bar
```

I wanted something like:

```
secret {
  ...
  format_username="MY_USER"
  format_password="MY_PWD"
}
```

generating

```
MY_USER=foo
MY_PWD=bar
```

Thanks in advance

**Comment by dekimsey** [comment]
I too ran into this issue. The `secret` keyword's functionality doesn't lend itself well to the other vault mount points.

I know I'd like more advanced templating support to customize how the the credentials are passed to the application (a URI example for instance). However, I suspect this may start to veer into consul-template's territory. But consul-template doesn't have support for exporting keys to the application. (With consul-template, right now I'm emitting a shell script I then source && shred && exec, which is the definition of clunky.)
