### ISSUE TITLE
flag provided but not defined: -exec-reload-signal

### ISSUE THREAD

**Issue by thesame00** [hashicorp/envconsul#237]
Hey,

I try to run a simple command: 
 envconsul -exec=echo --exec-reload-signal="HUP"
flag provided but not defined: -exec-reload-signal

but I get the above error. It -exec-reload-signal not supported anymore?

I use envconsul v0.9.2 (336bffc9) on Ubuntu 19.10 64 bit.

**Comment by eikenb** [comment]
Hey @thesame00, thanks for the report.

It looks like it was just missed. The configuration mostly reuses code from consul-template except for the cli argument processing, which is duplicated in envconsul. It looks like `-exec-reload-signal` flag was never parsed in envconsul. To add it we just need to add it to the parsed flags.

**Comment by thesame00** [comment]
hey @eikenb when do you think that v0.9.3 will be released?
Welcome!

**Comment by eikenb** [comment]
@thesame00 .. A co-worker  pointed out this bit in the README that I had forgotten about...
``` 
`exec.reload_signal` - This signal exists, but it is never used. Configuring it will have no affect, since Envconsul does not send reload signals to child processes.
```
I double checked and this was true. Sending the reload signal to envconsul reloads the config then kills and restarts the child process. It doesn't send signal to the child process at all on reloads.

Envconsul does send other signals onto the child process, except for those configured for kill_signal and reload_signal. And it does use the configured exec.kill_signal when terminating the child process.

I'm going to rework my PR to remove the exec-reload-signal from the cli help to avoid this confusion in the future.

I apologize for the confusion.

**Comment by eikenb** [comment]
> Envconsul does send other signals onto the child process [...]
 
To clarify this, what I mean is that all other signals, except those specifically configured (and SIGCHILD, which has special OS meaning), are sent onto the child process.

So say if you signal envconsul with SIGHUP (and it is not configured for kill_signal or reload_signal) it will signal the child process with SIGHUP as well.
