### ISSUE TITLE
Provide a mechanism to query the latest release for envconsul

### ISSUE THREAD

**Issue by JonZeolla** [hashicorp/envconsul#251]
### Expected behavior
I can anonymously query an endpoint receive JSON in the response body that contains latest version of `envconsul`.

### Actual behavior
There are no github releases, and https://checkpoint-api.hashicorp.com does not have a `envconsul` endpoint.

### Steps to reproduce
1. No github releases: `curl https://api.github.com/repos/hashicorp/envconsul/releases` returns an empty list
2. No endpoint on the checkpoint-api: `curl https://checkpoint-api.hashicorp.com/v1/check/envconsul` returns a 404

**Comment by JonZeolla** [comment]
@findkim any idea where this fits into the priorities?  I would be willing to contribute if there is a preferred approach in mind.

**Comment by eikenb** [comment]
Hello again @JonZeolla... said this on a similar issue for consul-template but wanted to repeat it here for the viewing audience. 

We have a new release pipeline that we will be converting these projects over to soon and I'm pretty sure it does github releases as part of the process. You can see it in action with our [new project](https://github.com/hashicorp/consul-terraform-sync/) (which is nearing its initial release).

**Comment by JonZeolla** [comment]
Wonderful, thank you (again) for the update.  I will stay tuned

**Comment by JonZeolla** [comment]
Are you open to external contributions to the conversion?

**Comment by eikenb** [comment]
Answered same question under consul-template. Linking instead of C-n-P-ing.

https://github.com/hashicorp/consul-template/issues/1437#issuecomment-818993205

**Comment by iniinikoski** [comment]
@JonZeolla I was pondering around this as well, but as we are working with Dockerfiles here, I was just able to do this: 

```
FROM hashicorp/envconsul:latest as envconsul
COPY --from=envconsul /bin/envconsul /usr/local/bin/envconsul
```

Just to let you know...

**Comment by JonZeolla** [comment]
Thanks!  We avoided that approach to ensure we have reproducible builds in addition to version pinning.

**Comment by eikenb** [comment]
The last 2 releases have used github's release system so the https://api.github.com/repos/hashicorp/envconsul/releases URL now returns them. Thanks!

**Comment by JonZeolla** [comment]
Thank you!  I've confirmed that this solves my issue
