### ISSUE TITLE
envconsul can not work with mongo cli

### ISSUE THREAD

**Issue by zffocussss** [hashicorp/envconsul#263]
Please note that the envconsul issue tracker is reserved for bug reports and
enhancements. For general usage questions, please use the Consul Community
Portal or the Consul mailing list:

    https://discuss.hashicorp.com/c/consul
    https://groups.google.com/forum/#!forum/consul-tool

mongo wrapped with envconsul can not read environment variables which are in store on consul.but when it is right with env directly
```
envconsul -prefix app/ env | grep MONGODB_DATABASE_HOST
MONGODB_DATABASE_HOST=mongodb://localhost/test2
```

### Envconsul version
envconsul v0.11.0 (9f66f6c5)

### Configuration
```hcl
no configuration
```

### Command
```shell
consul kv put app/MONGODB_DATABASE_HOST mongodb://localhost/test2
envconsul -prefix app/ mongo $MONGODB_DATABASE_HOST
```

### Debug output
Provide a link to a GitHub Gist containing the complete debug output by running
with `-log-level=debug`.

### Expected behavior
What should have happened?
mongo can connect with mongodb according to the connection string referred by $MONGODB_DATABASE_HOST

### Actual behavior
What actually happened?
$MONGODB_DATABASE_HOST is blank

### Steps to reproduce
1.consul put
2.envconsul -prefix
3.

### References
Are there any other GitHub issues (open or closed) that should be linked here?
For example:

- GH-1234
- ...

**Comment by eikenb** [comment]
Hey @zffocussss,

I think it should be working, but your test isn't seeing it for some reason. If I re-run your test with a slight change to the command it works fine...

```sh
$ consul kv put app/MONGODB_DATABASE_HOST mongodb://localhost/test2
Success! Data written to: app/MONGODB_DATABASE_HOST
$ envconsul -prefix app env | grep MONGO
MONGODB_DATABASE_HOST=mongodb://localhost/test2
$ envconsul -prefix app/ 'sh -c "echo $MONGODB_DATABASE_HOST"'
mongodb://localhost/test2
```

My initial guess is you are not properly quoting your command and it is trying to expand the `$MONGODB_DATABASE_HOST` variable using your current shell environment instead of the one created by envconsul to evaluate the command in.

Hope this helps.

**Comment by zffocussss** [comment]
> Hey @zffocussss,
> 
> I think it should be working, but your test isn't seeing it for some reason. If I re-run your test with a slight change to the command it works fine...
> 
> ```shell
> $ consul kv put app/MONGODB_DATABASE_HOST mongodb://localhost/test2
> Success! Data written to: app/MONGODB_DATABASE_HOST
> $ envconsul -prefix app env | grep MONGO
> MONGODB_DATABASE_HOST=mongodb://localhost/test2
> $ envconsul -prefix app/ 'sh -c "echo $MONGODB_DATABASE_HOST"'
> mongodb://localhost/test2
> ```
> 
> My initial guess is you are not properly quoting your command and it is trying to expand the `$MONGODB_DATABASE_HOST` variable using your current shell environment instead of the one created by envconsul to evaluate the command in.
> 
> Hope this helps.

yes you are right

**Comment by eikenb** [comment]
Great! Glad that worked.
