### ISSUE TITLE
load multiple keys

### ISSUE THREAD

**Issue by grosser** [hashicorp/envconsul#27]
we will be using 1 consule for a bunch of apps and it would be nice to reuse some shared config, like `envconsule global,some_concern,app_specific` without having to nest 3 enconsul calls `envconsule global envconsul some_concern envconsul app_specific` or load them into the env as suggested in https://github.com/hashicorp/envconsul/issues/3 do you think that's a good usecase ?

**Comment by sethvargo** [comment]
As discussed, you can now use the `-prefix` option to specify multiple prefixes. Their merging order is described in the READMe.

**Comment by grosser** [comment]
:heart: that looks great :)
