### ISSUE TITLE
Binary for darwin-arm64 (M1 Macs)

### ISSUE THREAD

**Issue by daturkel** [hashicorp/envconsul#276]
Hello, as of [envconsul 0.12.1](https://releases.hashicorp.com/envconsul/0.12.1/), Hashicorp doesn't ship darwin-arm64 binaries for envconsul. Since this is a Go project, I believe that supporting the platform is simply a matter of building with GOOS=darwin and GOARCH=arm64. Is it possible to get official darwin-arm64 builds added to the releases site? This is needed in order to use envconsul on M1 Macs (without resorting to [Rosetta](https://support.apple.com/en-us/HT211861)).

**Comment by eikenb** [comment]
Our next release will use our new build system which will support creating binaries for more platforms, including darwin/arm64. I'll tag this for the next release as that should resolve it.

Note I just finished a batch of consul-template work but I have to work on a consul-esm release first and then will be working on envconsul.

**Comment by lren90** [comment]
hey @eikenb, any timeline for the darwin/arm64 release?

**Comment by eikenb** [comment]
@lren90 ... Envconsul work is in my queue after the consul-esm release, but that is probably a few months off. I might be able to do something before that if you have no workarounds. I can look into that if needed. Let me know. Thanks.

**Comment by tuananh170489** [comment]
> Hello, as of [envconsul 0.12.1](https://releases.hashicorp.com/envconsul/0.12.1/), Hashicorp doesn't ship darwin-arm64 binaries for envconsul. Since this is a Go project, I believe that supporting the platform is simply a matter of building with GOOS=darwin and GOARCH=arm64. Is it possible to get official darwin-arm64 builds added to the releases site? This is needed in order to use envconsul on M1 Macs (without resorting to [Rosetta](https://support.apple.com/en-us/HT211861)).

You should use brew to install it
`brew install envconsul`

**Comment by eikenb** [comment]
v0.13.0 was released today which includes a Darwin Arm64 build. Please file a ticket if there are any issues with it. Thanks!
