### ISSUE TITLE
The cmd line option "-once" help text is wrong/misleading

### ISSUE THREAD

**Issue by simonellefsen** [hashicorp/envconsul#280]
### Envconsul version
v0.12.1 (265f933)

### Command
```shell
envconsul -h
```

### Debug output
```text
  -once
      Do not run the process as a daemon
```
### Expected behavior
A more accurate help text like what is actually in the code https://github.com/hashicorp/envconsul/blob/main/runner.go#L69-L70
`// once indicates the runner should get data exactly one time and then stop.`

The text, in my mind, "Do not run the process as a daemon" is more like run envconsul in the foreground and does not tell the user that data would only be fetched exactly once.

**Comment by eikenb** [comment]
Thanks for the report @simonellefsen! I'll be sure this gets fixed in the next release.
