### ISSUE TITLE
Pushing secrets to Environment file

### ISSUE THREAD

**Issue by whitepiratebaku** [hashicorp/envconsul#298]
I was not able to find a option to push env variables to file. For our situation we willing to write key value pairs to env file and use in Docker. I know we can setup Dockerfile to fetch them directly from Vault but because of Network restrictions we can`t.

**Comment by whitepiratebaku** [comment]
I see there is -pristine option which do not inherit existing env values, using this option and piping output to file should help thank you. I think this issue can be closed

**Comment by eikenb** [comment]
You could also take a look at consul-template. It works similarly to envconsul but writes to a templated file. It has support for environment variables. Envconsul uses it as a library.

https://github.com/hashicorp/consul-template

Just in case you hadn't see it yet. Thanks for following up.
