### ISSUE TITLE
Envconsul should propagate received signals to child process

### ISSUE THREAD

**Issue by inean** [hashicorp/envconsul#31]
There's no easy way to use envconsul with a service manager like superivisor or systemd. Problem IMHO is that envconsul doesn't propagate received signals to child process, and there's no easy way for service managers to get knowledge of grandchildren existence.
One possible solution is to propagate envconsul received signals to child process.

**Comment by armon** [comment]
Makes sense!

**Comment by n0n0x** [comment]
+1 to this

**Comment by sethvargo** [comment]
This is now present in master, with one caveat. We cannot handle _every_ signal, so we have restricted it to those listed in signals.go (or signals_windows.go if you are on windows). This includes the most common signals such as TERM, QUIT, INT, USR1, and USR2.
