### ISSUE TITLE
v0.13.0 keeps renewing credentials/restarting program every 1-2 minutes

### ISSUE THREAD

**Issue by simonellefsen** [hashicorp/envconsul#310]
### Envconsul version
0.13.0

### Configuration
```hcl
log_level = "trace"
kill_signal = "SIGINT"
reload_signal = "SIGHUP"
upcase = true

exec {
  splay = "5s"
  kill_signal = "SIGTERM"
  kill_timeout = "5s"
}

consul {
  address = "consul:8500"
  retry {
    enabled = true
    attempts = 3
    backoff = "250ms"
    max_backoff = "1m"
  }
}

vault {
  address = "https://vault:8200"
  ssl {
    enabled = true
    verify  = false
  }
  renew_token = true
  retry {
    enabled = true
    attempts = 3
    backoff = "250ms"
    max_backoff = "1m"
  }
}

#
# VAULT KEYS
#
secret {
  path = "_vault/aws/sts/internal-envconsul-example/"
}
secret {
  path = "_vault/rabbitmq/amqp/creds/internal-envconsul-example/"
}
secret {
  path = "_vault/secret/example/"
}
#
# CONSUL KEYS
prefix {
  no_prefix = false
  path = "_consul/example"
}
```

### Debug output

2022-08-15T08:11:38.828Z [TRACE] envconsul: vault.read(_vault/aws/sts/internal-envconsul-example): non-renewable secret, set sleep for 1m25.828049225s

### Expected behavior
With version 0.12.1 we got log stmts with more reasonable sleep values - ~55m which made sense with 1h AWS session token.

2022-08-15T08:17:47.355Z [TRACE] vault.read(_vault/aws/sts/internal-envconsul-example): non-renewable secret, set sleep for 56m22.590058722s

The credentials returned by vault setup gives us an 1hr lease, so we would have expected the credentials to be renewed every hour and not every minute. And as I wrote the setup works fine with envconsul v0.12.1

```
Key                Value
---                -----
lease_id           _vault/aws/sts/internal-envconsul-example/kJyMg0sMyaZhpa15VgOSCulo
lease_duration     59m59s
lease_renewable    false
access_key         ASIATDDRE5J7XZ....
secret_key         LH+waJXE5zoj2jvr/8ZTaXHyqu3....
security_token     FwoGZX....
```

### Actual behavior
Our program was restarted with new AWS STS token every 1-2 minutes.

### References
Are there any other GitHub issues (open or closed) that should be linked here?
For example:

- GH-1234
- ...

**Comment by eikenb** [comment]
Hey @simonellefsen, thanks for reporting this.

I'm currently looking into the issue and had an initial quick question. Which secrets engines are used in your example? Based on the naming I'd guess AWS, Database and K/V v1. Please let me know if I'm right or, if wrong, please let me know which engines they use.

Thanks.

**Comment by simonellefsen** [comment]
Hey @eikenb 

Yes you are right in your assumptions it is AWS.

I have tried to narrow it down.

Using session tokens endpoint `sts` fails with 0.13.0 renewing credentials every ~2 minutes or so. It clearly has something to do with the trace log message `non-renewable secret, set sleep for 2m48.909940418s` and this low sleep cycle causes renewals every 2m48s - in the preveious version 0.12.1 the sleep value would be closer to the actual ttl on the lease (60m).

```
2022-08-24T07:49:50.430Z [TRACE] envconsul: vault.read(_vault/aws/sts/internal-envconsul-example): GET /v1/_vault/aws/sts/internal-envconsul-example
2022-08-24T07:49:50.555Z [TRACE] envconsul: vault.read(_vault/aws/sts/internal-envconsul-example): non-renewable secret, set sleep for 2m48.909940418s
2022-08-24T07:49:50.555Z [TRACE] envconsul: (view) vault.read(_vault/aws/sts/internal-envconsul-example) marking successful data response
2022-08-24T07:49:50.555Z [TRACE] envconsul: (view) vault.read(_vault/aws/sts/internal-envconsul-example) successful contact, resetting retries

```

The lease returned from the aws sts endpoint looks like

```
% vault read _vault/aws/sts/internal-envconsul-example
Key                Value
---                -----
lease_id           _vault/aws/sts/internal-envconsul-example/l01bz4XMap5uv1UAP20dLbIZ
lease_duration     1h
lease_renewable    false
access_key         ASIATLE.....
secret_key         /x3ELznsjs.....
security_token     FwoGZXIvY....

```

I then tried using the AWS postgres endpoint - lease duration is the same except this lease is renewable

```
% vault read _vault/postgresql/instance/creds/internal-envconsul-example
Key                Value
---                -----
lease_id           _vault/postgresql/instance/creds/internal-envconsul-example/8kqJwokmBy9Wd0gIOWuA8k8I
lease_duration     1h
lease_renewable    true
password           wVUW.....
username           nQHJpsxtcE......

```

And this works just fine - it has to do with non-renewable tokens/secrets.

My guess is that something has changed in the https://github.com/hashicorp/consul-template/blob/main/dependency/vault_common.go#L110 `func leaseCheckWait(s *Secret) time.Duration {` causing this function to return a much smaller value than it used to.

**Comment by eikenb** [comment]
Hey @simonellefsen, sorry for the delay. Went out of town for a few days.

I think you have a bead on the issue. There was a change in leaseCheckWait between versions and it looks like that is the cause. Initially I thought it might be a default not getting set correctly, but the config was right... but for the new `VaultLeaseRenewalThreshold` configuration setting updates a module level variable from the config once running. This is an extra step only one other configuration variables has and it is not being called is the issue.

You can see it called in consul-template here...
https://github.com/hashicorp/consul-template/blob/97739ef75e1c35fa97d0c35abb1936f00a778698/manager/runner.go#L901

Anyways, I've reproduced it and confirmed that this is the issue and will have a fix up soon. I'll probably do a quicky followup bugfix release as this is pretty critical/breaking.

Thanks a ton for finding this!
