### ISSUE TITLE
no way to disable -sanitize or -upcase

### ISSUE THREAD

**Issue by rhelmer** [hashicorp/envconsul#34]
"-sanitize" and "-upcase" were made ```true``` by default in 84c04ff, so there's no way to disable this behavior.

Should the flags be changed to ```-no-sanitize``` and ```-no-upcase``` instead?

**Comment by mitchellh** [comment]
You should be able to do `-sanitize=false` and so on. Let us know if this doesn't work!

**Comment by rhelmer** [comment]
Yep that works, thanks!
