### ISSUE TITLE
A very minor issue regarding the Redis example in the README

### ISSUE THREAD

**Issue by dvusboy** [hashicorp/envconsul#37]
Specifically, this snippet:

```bash
$ envconsul \
  -consul demo.consul.io \
  redis/config service redis start
```

would have the intended effect because the standard ```service``` script do scrub the environment. For example, in ```initscripts-9.61```, you can see this snippet in the ```service``` script:

```bash
   env -i PATH="$PATH" TERM="$TERM"  SYSTEMCTL_IGNORE_DEPENDENCIES=${SYSTEMCTL_IGNORE_DEPENDENCIES} SYSTEMCTL_SKIP_REDIRECT=${SYSTEMCTL_SKIP_REDIRECT} "${SERVICEDIR}/${SERVICE}" ${ACTION} ${OPTIONS}
```

With that ```env -i```, all the environment variables will be ignored.

**Comment by dvusboy** [comment]
The solution may be this:

```bash
$ envconsul \
  -consul demo.consul.io \
  redis/config /etc/init.d/redis start
```

**Comment by sethvargo** [comment]
Thanks!
