### ISSUE TITLE
Support adding a prefix to generated environment keys

### ISSUE THREAD

**Issue by gozer** [hashicorp/envconsul#40]
Right now, consul keys map directly to the environment variable name (excluding upper-casing and sanitazion).

It would be handy if one could also specify a prefix to use for these environment variables, something like

--env-prefix=CONSUL_

**Comment by beberlei** [comment]
Additionally it would be super if the prefix leading to the key could also be dropped, I now have keys:

    apps/www/mysql/database=mysql://
    apps/www2/mysql/database=mysql://

When running envconsul with `envconsul -prefix=apps/www env` the env variables are:

   APPS_WWW_MYSQL_DATABASE=mysql://....

However i would like to have:

    MYSQL_DATABASE=mysql://...

**Comment by beberlei** [comment]
Sorry, i can just correct. This is a bug in envconsul when starting `-prefix=/apps/www` instead of `-prefix=apps/www` - Sorry :)

**Comment by sethvargo** [comment]
@gozer revisiting this - I think it might make more sense to take a more "Go-like" approach here and allow the user to specify a template for formatting a key. For example:

```shell
envconsul -prefix foo -format '{{ printf "consul_%s" | toUpper }}'
```

What do you think? Then we could actually deprecate the `-sanitize` and `-upcase` options in favor of a more verbose, user-customizable template. Thoughts?

/cc @armon @ryanuber
