### ISSUE TITLE
envconsul v0.5.0 still doesn't run when consul is unavailable

### ISSUE THREAD

**Issue by mhamrah** [hashicorp/envconsul#42]
If Consul is not running locally, I expect running an env command to return the current environment. See the following output:

```
root@762ae53f45ce:/# envconsul --prefix some_key env
2015/03/31 20:45:29 [ERR] (view) "storeKeyPrefix(some_key)" Get http://127.0.0.1:8500/v1/kv/some_key?recurse=&wait=60000ms: dial tcp 127.0.0.1:8500: connection refused
2015/03/31 20:45:29 [ERR] (runner) watcher reported error: Get http://127.0.0.1:8500/v1/kv/some_key?recurse=&wait=60000ms: dial tcp 127.0.0.1:8500: connection refused
^C2015/03/31 20:45:32 [WARN] (runner) attempted to send interrupt to subprocess, but it does not exist
Received interrupt, cleaning up...
root@762ae53f45ce:/# envconsul --version
envconsul v0.5.0
root@762ae53f45ce:/#

```

**Comment by armon** [comment]
@mhamrah Could you clarify the use case? In most uses of envconsul it is fetching non-optional configuration, so if Consul is not available and the prefix cannot be read then an error exit seems to be the only sane option.

**Comment by mhamrah** [comment]
I thought this was fixed with
https://github.com/hashicorp/envconsul/issues/28. Am I misunderstanding
that problem, or was it rolled back?

That issue seems to cover the use case. I use a custom launch script that
spits out a warning, but still continues to launch. Apps should have
environment variable fallbacks and/or exit if not set- shouldn't be an
envconsul concern imo.

How that makes sense.

Mike

**Comment by armon** [comment]
I think issue #28 is likely still there. However with the fix that went in, if you have no prefix values specified and Consul is not running it should avoid an error.

I think it makes sense for envconsul to handle the case of Consul failing after it starts, and continue to use the old values until Consul recovers / restarts. But it seems strange to start without any values on error. I think that would be a very surprising behavior for most users.

There is maybe some cases were a flag like `-ignore-error` could be used to allow starting with an error if you know your application can handle the environment variables not being set, but certainly unlikely to be the default.

**Comment by mhamrah** [comment]
Ahh, I see. Makes sense. I'll close this issue, and if you choose to add -ignore-error great, but I can easily make due without it.
