### ISSUE TITLE
Wait being overwritten

### ISSUE THREAD

**Issue by mhamrah** [hashicorp/envconsul#43]
If I specify a wait of "5s:10s", either in the config file or via -wait, envconsul reloads immediately after a key change. Look at the following log output:

```
2015/04/07 00:05:27 [INFO] (runner) quiescence timers starting
2015/04/07 00:05:27 [INFO] (runner) quiescence minTimer fired
2015/04/07 00:05:27 [INFO] (runner) running
```

I would expect minTimer to be fired 5s after the timer starts. 

Here are my other config values:

wait = "5s:10s"                                       
max_stale = "10s"
timeout = "30s"
upcase = true
sanitize = true
retry = "10s"

**Comment by sethvargo** [comment]
Hi @mhamrah 

I am sorry you are having issues with envconsul. Could you please run the command in debug mode and gist the output?

**Comment by mhamrah** [comment]
Sure, here are the relevant snippets:

I added a key to trigger the refresh

https://gist.github.com/mhamrah/f8fa24019777f74ca13b

**Comment by sethvargo** [comment]
Awesome thanks! Labeled as a bug.
