### ISSUE TITLE
Configurable signal on reload?

### ISSUE THREAD

**Issue by alexmic** [hashicorp/envconsul#45]
It would be great if we could configure the signal to send on reload. We're thinking of running gunicorn with `envconsul` and we'd like to send a HUP to the master which will gracefully reload the workers. Do you think that makes sense?

**Comment by sethvargo** [comment]
Hi @alexmic 

That sounds like a good idea. Would you like to submit a PR for that? I think you'll just want to make [this](https://github.com/hashicorp/envconsul/blob/721f73c435cb49bb1db8557ae0597e1a3560e65e/runner.go#L352) something the user can supply via the command line and/or config.

**Comment by alexmic** [comment]
Cool, I will take a look when I have some time.

**Comment by aantono** [comment]
Downloaded the source and tried to run a newly-built application, but does not look like --killsig option is working.
When trying to run ```envconsul --sanitize --upcase --killsig SIGHUP```
getting this error:
```2015/06/14 01:36:03 [ERR] flag provided but not defined: -killsig```

**Comment by sethvargo** [comment]
@aantono see 3ccc20f

**Comment by aantono** [comment]
Tried the ```--kill-sig SIGHUP``` as well, but still no luck.  Continue getting this error:
```
./bin/envconsul --kill-sig SIGHUP --prefix / env
flag provided but not defined: -kill-sig

Usage: envconsul [options]

  Watches values from Consul's K/V store and sets environment variables when
  Consul values are changed.

Options:

  -auth=<user[:pass]>      Set the basic authentication username (and password)
  -consul=<address>        Sets the address of the Consul instance
  -max-stale=<duration>    Set the maximum staleness and allow stale queries to
                           Consul which will distribute work among all servers
                           instead of just the leader
  -ssl                     Use SSL when connecting to Consul
  -ssl-verify              Verify certificates when connecting via SSL
  -token=<token>           Sets the Consul API token

  -syslog                  Send the output to syslog instead of standard error
                           and standard out. The syslog facility defaults to
                           LOCAL0 and can be changed using a configuration file
  -syslog-facility=<f>     Set the facility where syslog should log. If this
                           attribute is supplied, the -syslog flag must also be
                           supplied.

  -wait=<duration>         Sets the 'minumum(:maximum)' amount of time to wait
                           before writing a triggering a restart
  -retry=<duration>        The amount of time to wait if Consul returns an
                           error when communicating with the API

  -prefix                  A prefix to watch, multiple prefixes are merged from
                           left to right, with the right-most result taking
                           precedence
  -sanitize                Replace invalid characters in keys to underscores
  -upcase                  Convert all environment variable keys to uppercase


  -config=<path>           Sets the path to a configuration file on disk

  -log-level=<level>       Set the logging level - valid values are "debug",
                           "info", "warn" (default), and "err"

  -once                    Do not run the process as a daemon
  -version                 Print the version of this daemon
2015/06/14 11:14:28 [ERR] flag provided but not defined: -kill-sig
```

Running ```envconsul``` built from ```master``` on OS X Yosemite 10.10.3 built with Go 1.4
```
go version
go version go1.4 darwin/amd64
```

**Comment by aantono** [comment]
Upon further trials, looks like using ```--kill-signal SIGHUP``` does work.
The interesting consequence observed, is that the application is still being restarted, after the ```SIGHUP``` signal has been sent, which might be defeating the purpose of using an alternative signal, or at least diminishing the functional value of it.
If I also specify ```--once```, then the configuration change within Consul is not being monitored, so no signal is being sent at all.   I would like to propose to add another option, ```--no-restart```, which, if specified, would only send the ```--kill-signal``` to the running application process, but do not attempt to restart it.  This way, once can implement a functionality of internal configuration reloading without restarting the application by combining ```--kill-signal SIGHUP``` with ```--no-restart``` and that would let the running application internally reload the data without shutdown.    Thoughts?
