### ISSUE TITLE
Add support for Vault

### ISSUE THREAD

**Issue by sethvargo** [hashicorp/envconsul#46]
Refs: https://github.com/hashicorp/vault/issues/89

**Comment by svnlto** [comment]
Any news on this?

**Comment by sethvargo** [comment]
Hi @svnlto 

This has not been a heavily-requested feature by users, so it's mostly on the back-burner for now :smile:

**Comment by svnlto** [comment]
I guess I'll stick to consul + vault then :smile:

**Comment by avthart** [comment]
I am also interested in this feature. We want to use consul for storing application config. This config can contain database passwords, etc.

**Comment by jstremick** [comment]
:+1:  Would love to have this.

**Comment by zarry** [comment]
+1 would like this!

**Comment by msabramo** [comment]
:+1:

**Comment by jippi** [comment]
:+1:

**Comment by greggilbert** [comment]
:+1:. Would be amazing.

**Comment by WillPlatnick** [comment]
:+1: as well.

**Comment by partek** [comment]
:+1:

**Comment by aehlke** [comment]
:+1: though it would be great to gather this feedback some other way, this thread is very noisy to subscribe to. Thanks.

**Comment by ekristen** [comment]
+1

**Comment by sudarkoff** [comment]
Hey, @sethvargo, any word on when we might expect this released?

**Comment by sethvargo** [comment]
@sudarkoff we are focusing on HashiConf right now

**Comment by sethvargo** [comment]
Hey all :smile: 

I just opened #69 which is the first pass at adding Vault support. It still needs technical code review from my colleagues at HashiCorp, but I would love some usage feedback from you all since you expressed interest in this feature.

You can checkout the `sethvargo/vault` branch and build a local release `make updatedeps && make dev` and try it out :smile:
