### ISSUE TITLE
Support --no-restart with --kill-signal to NOT always restart the application

### ISSUE THREAD

**Issue by aantono** [hashicorp/envconsul#52]
When testing with --kill-signal SIGHUP an interesting behavior was observed. The application is still being restarted, after the SIGHUP signal has been sent, which might be defeating the purpose of using an alternative signal, or at least diminishing the functional value of it.
If I also specify --once, then the configuration change within Consul is not being monitored, so no signal is being sent at all. I would like to propose to add another option, --no-restart, which, if specified, would only send the --kill-signal to the running application process, but do not attempt to restart it. This way, one can implement a functionality of internal configuration reloading without restarting the application by combining --kill-signal SIGHUP with --no-restart and that would let the running application internally reload the data without shutdown. Thoughts?

**Comment by sethvargo** [comment]
@aantono SIGHUP is an application-specific thing. If the application restarts on SIGHUP, there's not much envconsul can do about that.

**Comment by aantono** [comment]
@sethvargo , Are you sure that envconsul does not force-kills the application, when the configuration changes, if it does not go away after the signal is sent?  The application I was testing it with does not terminate upon sending the SIGHUP directly to the process, but envconsul seems to always kill it. :(

I think https://github.com/hashicorp/envconsul/blob/master/runner.go#L175 is making it always terminate the process, if I read the code correctly.

**Comment by x-cray** [comment]
This line https://github.com/hashicorp/envconsul/blob/master/runner.go#L387 suggests that process is forced to quit if it didn't do that within specified timeout by itself.

**Comment by ryanuber** [comment]
You are correct that envconsul will force the child to exit. Currently envconsul handles config reloads by replacing the child process entirely. It would be nice to support applications which can tolerate a config reload, so I'm marking this as an enhancement. Thanks!

**Comment by x-cray** [comment]
+1. Such --no-restart option would also indirectly solve #54 — one can create a wrapper shell script with traps for different signals and call external tools whenever trap is hit.

**Comment by sethvargo** [comment]
Hi all,

In our testing, we found this is actually _not possible_ :frowning:. Once the process is started by go's exec, there's no way to replace the environment. Even if you update the env map and send a reload signal to the child process, the environment is never updated. This was likely an intentional design decision of the framework, but unfortunately this is not something we are able to work around.

As such, envconsul will always need to kill and re-spawn the application in order for the application to pick up the new environment variables. Sorry!
