### ISSUE TITLE
Add splay option

### ISSUE THREAD

**Issue by mfischer-zd** [hashicorp/envconsul#53]
A `splay` option argument would be useful to complement the existing `wait` option argument.  The value of the `splay` option would be a maximum time in seconds to wait before restarting the program under envconsul's control, from which a random value would be chosen.  This would help prevent a thundering herd of synchronized application restarts that could take down a service entirely.

Example: `envconsul ... -splay 60 /path/to/program`

**Comment by jhmartin** [comment]
How about placing locking on some key such that envconsul will only restart X processes concurrently?
