### ISSUE TITLE
envconsul -reload option?

### ISSUE THREAD

**Issue by sergiomerino** [hashicorp/envconsul#60]
just read a post in your blog - https://hashicorp.com/blog/twelve-factor-consul.html- where you are talking about configuration management & environment variables...

Specifically, my question is related with -reload option of envconsul that you mention in this post...

I´m testing envconsul v0.5 and it seems like this option doesn´t exist. is it correct?

 [ERR] flag provided but not defined: -reload

**Comment by ryanuber** [comment]
This behavior was changed in envconsul 0.3. This is now the default behavior, so specifying the `-reload` argument is no longer required! See the [changelog](https://github.com/hashicorp/envconsul/blob/f8c1fd854bec2a02d6ea7d1374c8e3fe964f7a8a/CHANGELOG.md#v030-november-4-2014) for more details.
