### ISSUE TITLE
Prevent envconsul from sending a signal to the child process.

### ISSUE THREAD

**Issue by brycechesternewman** [hashicorp/envconsul#62]
Hello,
I have about ten applications that all use the same keys in Consul but they each need different values. I want to make a change to the value in Consul but I don't want envconsul to send a signal to my all my applications and I want to restart the applications manually. The --once will not work here since I still want to daemonize envconsul. 
I have some options in my arsenal; catch the signal in scala and don't restart(not always possible), modify how we create keys in consul to not use the same key root and lastly does envconsul have the ability to turn off sending signals - perhaps some command line arg I don't see that is not --once?
Thank you.

**Comment by sethvargo** [comment]
@brycechesternewman 

Why does the `--once` flag not work here? If you want to manually control the signal cycle, that's what once will do. envconsul will still run as long as the child command does not exit, so it's possible to daemonize it. Then, when you want to trigger an update, just send SIGHUP to the envconsul process.

**Comment by brycechesternewman** [comment]
If it works then great!
The documentation threw me off and that is why I asked. The docs say that envconsul runs once then exists "Run envconsul once and exit (as opposed to the default behavior of daemon). (CLI-only)"
