### ISSUE TITLE
envconsul appears to swallow input

### ISSUE THREAD

**Issue by cddr** [hashicorp/envconsul#75]
I think envconsul is swallowing STDIN rather than passing it along to the app it runs. I'm running version 0.5.

### Expected
```
/ # echo "foo" |cat
foo

/ # echo "foo" |envconsul -consul $CONSUL:8500 -prefix yolo cat
foo
```

### Actual
```
/ # echo "foo" |envconsul -consul $CONSUL:8500 -prefix yolo cat
```

The /etc/envconsul-config.hcl looks like this

```
sanitize = true
upcase = true
wait = "2s:8s"
```

/cc @aprobus

**Comment by nachomdo** [comment]
@cddr I found the same issue

**Comment by cddr** [comment]
Thanks Seth.
