### ISSUE TITLE
Feature Request: change vault key representation

### ISSUE THREAD

**Issue by mumblez** [hashicorp/envconsul#77]
Just like how consul's key is represented, can we have a way to do the same for vault, e.g. just the last part of the path instead of the entire path.

e.g.
vault path: secret/app/prod/mysql
current environment variable = SECRET_APP_PROD_MYSQL_{some key}
preferred format = MYSQL_{some key}

The preferred format option available in the options seems to only allow us to prefix and append to the current former representation (before and after {{ key }}).

I understand this might be tricky as vault's path represents a struct type key value where as in consul it's a key.

Some discussion - https://groups.google.com/forum/#!topic/consul-tool/EGO0vljG1KI

**Comment by sethvargo** [comment]
Hi @mumblez 

Thank you for using envconsul and thank you for opening an issue. I was reading through that mailing list post this morning actually.

We intentionally decided to only allow prefixing of the key for a few reasons when implementing this functionality. I think @mfischer-zd's suggestion of wrapping the script if your application needs a specific environment variable name is the best approach:

```bash
#! /usr/bin/env bash
export MY_VALUE="${SECRET_FOO_BAR_VALUE}"
exec /bin/my-app
```

Thanks! :smile:
