### ISSUE TITLE
Compiling envconsul v0.6.0

### ISSUE THREAD

**Issue by ch-acctg** [hashicorp/envconsul#78]
Hi, we have been successfully compiling/bundling envconsul in with our consul.  However, the past few weeks envconsul is failing to compile with errors very similar to what the official travis-ci is currently getting.  Are these some issues with external dependencies in Go?

**Comment by sethvargo** [comment]
What errors are you getting?

**Comment by ch-acctg** [comment]
The same ones you are getting :) -- https://travis-ci.org/hashicorp/envconsul

**Comment by sethvargo** [comment]
Ah - they are just bad tests that are due to a change in the HCL parser /cc @mitchellh @jen20

**Comment by sirlatrom** [comment]
@sethvargo So these can be safely ignored? Or will they have to pass for envconsul to be reliable?

**Comment by sethvargo** [comment]
It's fine. I'll fix when we release.
