### ISSUE TITLE
Envconsul Dependency on Consul

### ISSUE THREAD

**Issue by osterman** [hashicorp/envconsul#79]
Documentation does not mention if `envconsul` will work without a consul service; we only want to use envconsul with vault.

Use case: we want to use `vault` to manage our secrets, `envconsul` to provision ENVs pulled from `vault` and run our app, but continue to manage service discovery with zookeeper so we don't need to re-tool things. Would this work?

**Comment by sethvargo** [comment]
Hi @osterman 

You do not need consul to use envconsul - it will work with just Vault. Thanks!
