### ISSUE TITLE
Prefix is a little too unspecific

### ISSUE THREAD

**Issue by sprin** [hashicorp/envconsul#8]
I set keys:
`myapp/SECRET` to "foo"
`myapp2/SECRET` to "bar"

When I run:

```
/usr/bin/env -i /bin/envconsul -addr="sfo1.demo.consul.io:80" myapp /usr/bin/env
```

I see:

```
SECRET=foo
2_SECRET=bar
```

I think the intended behavior is to do an exact match on the prefix? If so, I would be happy to submit a PR for this.

Thanks for this neat little tool! So much nicer than extracting environment variables at deploy time! Here's how I was doing it before:
https://github.com/marina-lab/docker-registry-lab/blob/3fa1cce32cd98bf9e59db9d99614ca6b94d06da0/roles/docker_reg/tasks/main.yml#L10

**Comment by martinstreicher** [comment]
Is there a way to disable the prefixing? For instance, in this example, the `2_SECRET` variable would not be generated. To have some determinism, I would use multiple `-prefix` options to set the order. So, here, I might use `-prefix myapp -prefix myapp2` to yield `SECRET=bar`.

**Comment by martinstreicher** [comment]
@armon See above?
