### ISSUE TITLE
Cannot use envconsul with interactive applications

### ISSUE THREAD

**Issue by jsok** [hashicorp/envconsul#80]
Attempting to run `envconsul` with an application which is interactive causes the target application to immediately exit:

```
> envconsul -config=config.hcl -once bash
2015/12/07 11:10:12 looking at vault secret/password
> echo $?
0
```

Not sure if this is meant to be supported, but it would be handy for debugging!

**Comment by sethvargo** [comment]
Hi @jsok 

This is correct. envconsul does not (and cannot) allocate a tty, thus programs like `bash` will exit immediately. I would recommend using `env` for debugging instead:

```
$ envconsul -config=config.hcl -once env
```

This will print the entire env hash. If you really want a subshell, you could probably do something like:

```
$ export "$(envconsul -secret=secret/foo env)"
```

But I'm going to look at how difficult this might be to implement.

**Comment by jsok** [comment]
Yep makes sense, just wanted to make sure I hadn't missed something in the docs.
I'm happy to close the issue if you don't think it's worth pursuing, I'll let you decide!

**Comment by tspecht** [comment]
Is this working by now?

**Comment by sethvargo** [comment]
This works as of 235d234, which will be released this week or next.
