### ISSUE TITLE
Don't fail if secret not found?

### ISSUE THREAD

**Issue by l8nite** [hashicorp/envconsul#83]
Can envconsul look for secrets without failing if they're not found? 

For example:
```
2016/01/22 18:28:30 looking at vault secret/development/ccda_domain_database
2016/01/22 18:28:30 [ERR] (view) "vault(secret/development/ccda_domain_database)" no secret exists at path "\"vault(secret/development/ccda_domain_database)\""
2016/01/22 18:28:30 [ERR] (runner) watcher reported error: no secret exists at path "\"vault(secret/development/ccda_domain_database)\""
2016/01/22 18:28:30 [ERR] no secret exists at path "\"vault(secret/development/ccda_domain_database)\""
```

In this case, I'm fetching an environment-specific path for the secret ("development/"), and I want to allow the application to launch even if these values aren't present.

**Comment by sethvargo** [comment]
Hi @l8nite 

If you want the application to launch without those secrets, I would recommend building first-class support for Vault into your application instead of reading the values from the environment with envconsul. You could also just write empty values to those paths. Thanks!

**Comment by l8nite** [comment]
I'm actually building some container wrappers that will be working with a variety of different code bases. Updating the application code itself to pull from vault specifically is kind of a pain, but you gave me an idea that I can probably just shell-script querying vault myself and trapping errors.

**Comment by l8nite** [comment]
This is a bit ugly, but in case anyone else is looking for a similar solution. The below script will read from vault and consul and export any variables found into the shell (unless they're already set), then execute whatever command you pass to it.

I'm using this as the ENTRYPOINT in a run-once container which needs to pull configuration and secrets from consul and vault and then execute another process. 

```
vault_secrets_filename=$(mktemp)
if curl --fail --silent --connect-timeout 3 -H "X-Vault-Token: ${VAULT_TOKEN}" -X GET http://vault:8200/v1/secret/${APP_ENV}/${APP_NAME} > $vault_secrets_filename; then
  eval $(cat $vault_secrets_filename | jq -r '.data | to_entries[] | (.key | ascii_upcase | gsub("/";"_")) as $key | (.value) as $val | "export \($key)=${\($key):=\($val)}"')
else
  echo "Error connecting to vault! Bailing."
  exit 1
fi
rm -f $vault_secrets_filename

# read config values from consul and export into the shell
consul_config_filename=$(mktemp)
if curl --fail --silent --connect-timeout 3 -X GET http://consul:8500/v1/kv/config/${PF_ENV}/${PF_APP}?recurse=1 > $consul_config_filename; then
  eval $(cat $consul_config_filename | jq -r '.[] | (.Key | gsub("config/'"${APP_ENV}/${APP_NAME}"'/";"") | ascii_upcase | gsub("/";"_")) as $key | (.Value | @base64d) as $val | "export \($key)=${\($key):=\($val)}"')
else
  echo "Error connecting to consul! Bailing."
  exit 1
fi
rm -f $consul_config_filename

$@
```
