### ISSUE TITLE
Allow stripping (parts of) secret path

### ISSUE THREAD

**Issue by sirlatrom** [hashicorp/envconsul#84]
It's not unthinkable that one might structure secrets in the general backend like this:

```
secret/
  dev/
    thirdparty-service/
      password=foo
  staging/
    thirdparty-service/
      password=bar
```

Currently that results in the following env vars (if both are referred to using `-secret` flags):

```
secret_dev_thirdparty_service_password=foo
secret_staging_thirdparty_service_password=bar
```

It would be very practical for some use cases to be able to strip `secret_`, `secret_dev_`/`secret_staging` or `secret_dev_thirdparty_service`/`secret_staging_thirdparty_service` from the resulting environment variable names. This would correspond to how `-prefix` works.

**Comment by sethvargo** [comment]
Hi @sirlatrom 

Thank you for opening an issue. I do not think this something that has been widely requested, so we will probably not be implementing this ourselves. We would definitely welcome a community contribution though.

We are, however, very against stripping the `secret_` prefix for security reasons.

**Comment by dkhunt27** [comment]
I am facing the same issue.  The resulting secret path contains the environment.  This makes it difficult to parse the secret without adding in some logic that builds the variable to use with the environ name in it.

**Comment by vkhatri** [comment]
+1 It would be a great help to have `envconsul` returning just the secret value as `SECRET_NAME=SECRET_VALUE` without the complete `secret/...` path prefix, like it returns value for Consul key.

This makes it difficult to work with, as now we have to maintain the complete secret path in the code too which could be counter productive especially when working with multiple env/app/cluster etc. Currently, we are forced to use vault api to get the secrets due to this behavior.

**Comment by justechn** [comment]
+1 I would also like a shorter name that does not include the environment

**Comment by JoyPeterson** [comment]
I also need this feature to be able to remove the path prefix.  It would be nice to be able to do something like this:

```
secret {
  path = "secret/dev/thirdparty-service"
  format = "secret_{{ key_name }}"
}
```

When given the following structure:

```
secret/
  dev/
    thirdparty-service/
      username=dev-user
      password=foo
  staging/
    thirdparty-service/
      username=staging-user
      password=bar
```
it would result in the following environment variables:

```
secret_username=dev-user
secret_password=foo
```

Or maybe we also want to include secrets from the secret/staging/thirdparty-service path but we want to avoid collisions:

```
secret {
  path = "secret/dev/thirdparty-service"
  format = "secret_{{ key_name }}"
}

secret {
  path = "secret/staging/thirdparty-service"
  format = "secret_staging_{{ key_name }}"
}
```

This would would result in the following environment variables:

```
secret_username=dev-user
secret_password=foo
secret_staging_username=staging-user
secret_staging_password=bar
```

**Comment by chrisseto** [comment]
Probably should have read the issues first, apologies in advance if it does not, but I believe https://github.com/hashicorp/envconsul/pull/113 solves this (somewhat).

**Comment by daveadams** [comment]
I just want to throw in here that it is critical to be able to reformat the env var names so we can use envconsul to run a program where we don't have complete ownership of the code (either a vendor program or a third party code library). For now we have to wrap our program startup in another script that remaps the variable names. envconsul comes _so_ close to being a perfect solution except for this issue.

@sethvargo can you explain what security risk you have identified that you believe requires an enforced prefix?

**Comment by deepthawtz** [comment]
This behavior is frustrating and confusing.

So w/ the current implementation people have to either rename their environment variable strings in their code *OR* write their some kind of conversion to strip the Vault path prefix from the environment variable? Is that correct?

**Comment by daveadams** [comment]
Yeah even if we didn't mind changing our code, the current setup requires that you check differently-named env vars depending on your environment, which pretty much defeats the point of using env vars.

FWIW, here's the bash code I use to rename these (based on a config-management-injected variable indicating the prefix, although you could also feed that in from Consul I suppose):

    for vault_varname in $( set -o posix; set |cut -d= -f1 |grep "^$PREFIX_TO_STRIP" ); do
        new_varname=$( sed s/^${PREFIX_TO_STRIP}// <<< "$vault_varname" )
        eval "export ${new_varname}=\"\$${vault_varname}\""
        eval "unset ${vault_varname}"
    done

I have an init script that calls envconsul, but envconsul calls a wrapper script to handle that ^ before calling the actual program.

@sethvargo can you explain more what you mean by "security reasons" above?

**Comment by ianwestcott** [comment]
I'm in the process of rolling out Vault in my infrastructure, and I've just discovered this issue. I need to migrate secret data from another system into Vault for a number of applications. Those applications each have numerous environment variables that they expect to be named in a certain way. Thus, the compulsory prefix behavior for Vault secrets makes envconsul almost completely useless for my needs. 

As far as I can tell, the patch proposed in #113 (which has now been open for 3 months without review) will resolve this issue for me. Could someone review it, or explain why it's not a viable solution? 

Thanks.

**Comment by deepthawtz** [comment]
I gave up waiting and forked the project w/ that patch and it is working great for us.

**Comment by oleksandr** [comment]
There cases where you either can't place keys in the write path in Vault or can't rename them in the app. In this case envconsul/vault is as useful as tits on a fish.

**Comment by sethvargo** [comment]
Merged
