### ISSUE TITLE
envconsul does not check child process while consul connection dropped

### ISSUE THREAD

**Issue by StefanScherer** [hashicorp/envconsul#85]
We are running envconsul to start/restart a node.js app. In our tests we found a situation where envconsul does not handle crashed child processes.

Rough description to reproduce:

1.) start consul
2.) add some kv data
3.) start envconsul with the node.js app

then

4.) kill consul

so the connection drops. Now envconsul does not recognize crashes in the node.js app and does not exit.

5.) start consul again

then envconsul still does not come back into a valid state to check the child process.

In my opinion envconsul should 
* either crash/exit in case of 4.) consul connection drops
* work in "offline" mode to keep an eye to its child process providing the last known env values and recognize child exits

Do you need more details about the setup for this scenario?

**Comment by StefanScherer** [comment]
My colleage @scherermichael has built a small setup to show the two cases in this repo: https://github.com/plossys/envconsul-no-exit

* [good-case](https://github.com/plossys/envconsul-no-exit#good-casesh) shows the expected behavior if consul connection is still there
* [bad-case](https://github.com/plossys/envconsul-no-exit#bad-casesh) shows the unexpected behavior if the consul connection is lost

**Comment by StefanScherer** [comment]
@sethvargo Thank you! I'll try the fix #107 in our environment. What's the best way to get a new binary? It seems that GitHub releases/tags are a little bit out of sync with https://releases.hashicorp.com/envconsul/
Is there a new release planned in the near future? 
Otherwise I'll setup a travis/circle/appveyor build in a fork.

**Comment by sethvargo** [comment]
Hi @StefanScherer 

We do not use github releases anymore - we use our releases service: https://releases.hashicorp.com. You can also build from source pretty easily - just install go 1.6 and run `make dev` on your local machine to build a binary. If you want to build linux binaries, you can set the XC_OS and XC_ARCH flags and run `make bin`.

**Comment by scherermichael** [comment]
Hi @sethvargo

I just tested the new version with our test case and can confirm that it works well now. Thank you very much!

**Comment by aabed** [comment]
I am facing the same issue, but my environment is a little bit different , I've updated envconsul, yet I am having the same error

`2016/05/06 12:01:02 [ERR] (view) "storeKeyPrefix(url-redirect-adrelated/)" store key prefix: error fetching: Unexpected response code: 504
2016/05/06 12:01:02 [ERR] (runner) watcher reported error: store key prefix: error fetching: Unexpected response code: 504
`

I am running a node.js app inside pods on top of kubernetes

**Comment by sethvargo** [comment]
Hi @StefanScherer 

The error you are getting is different and probably not related to this issue. Could you please open a new issue and include the complete debug output?

**Comment by StefanScherer** [comment]
I'm fine with the fix.  Thank you!
-> ping @aabed

**Comment by aabed** [comment]
@sethvargo Thanks I will open a new one
@stefanscherer,Thanks

**Comment by koresar** [comment]
Hello future people trying to fix that issue. The new issue (and how to fix it) is in #109
