### ISSUE TITLE
Please support format feature on command line args.

### ISSUE THREAD

**Issue by skyscooby** [hashicorp/envconsul#86]
Prefix by itself seems to be supported but I can't seem to see a place in the code that accepts a prefix-format switch to enable this feature for a run once / command line invocation. This would be useful in situations where a -once run needed the ability to identify environments set via envconsul in a subprocess (to apply a template to the value for instance).

prefix {
  path   = "config/redis"
  format = "prod_{{ key }}"
}

**Comment by arthurtsang** [comment]
you can use -once with -config.  just that -once needs to be specified in the cli rather than in the hcl.  

```
envconsul -config config.hcl -once env
```

**Comment by skyscooby** [comment]
Thanks that's what I resorted to doing..  writing a one time config using a HERE DOC and running with that.. I just thought a switch would be easier.

**Comment by sethvargo** [comment]
Hi there,

You can specify the prefix on the CLI, but advanced options require a configuration file.
