### ISSUE TITLE
Optional prefix

### ISSUE THREAD

**Issue by tspecht** [hashicorp/envconsul#91]
Hey guys,

I was thinking about how I would structure the layout of my vars in Consul and was wondering if there is a possibility to get the same functionality as `prefix` currently provides but make it fail silently if no such key was found in Consul?
This would greatly help me overriding certain global vars as-needed in specialized sub-environments :)

**Comment by jippi** [comment]
are you sure `prefix`doesn't work "optionally" ? 

eg. `-prefix something/existing -prefix something/non-existing` may work ?

**Comment by jippi** [comment]
@tspecht

**Comment by sethvargo** [comment]
Hi there,

I just tested, and this is actually the behavior. If you enable logging, you'll see the warning, but the process continues happily when no value exists.
