### ISSUE TITLE
Using envconsul with Consul's service directory

### ISSUE THREAD

**Issue by marceldegraaf** [hashicorp/envconsul#93]
I'm trying to use envconsul to set the IP/port of a Consul service in the environment, so another application can connect to that service.

However, it seems that envconsul can only read from Consul's K/V store, not from the service directory. Is that correct or am I missing something?

Thanks!

**Comment by sethvargo** [comment]
Hi @marceldegraaf 

That is correct. Envconsul is designed to read from the key-value store. If you want to integrate with services, you should have a look at [Consul Template](https://github.com/hashicorp/consul-template). Thanks!

**Comment by marceldegraaf** [comment]
Thanks @sethvargo. Is it by design that envconsul doesn't read from the service directory? Is it something that you'd eventually want to support in envconsul?

I did consider using Consul Template, but using envconsul is much easier for applications that are only configurable with environment variables.

**Comment by sethvargo** [comment]
Hi @marceldegraaf 

envconsul is designed to only read from the K-V store.

**Comment by marceldegraaf** [comment]
OK, thanks @sethvargo.
