### ISSUE TITLE
release page download format consistency

### ISSUE THREAD

**Issue by stevecrozz** [hashicorp/envconsul#94]
On the releases page: https://github.com/hashicorp/envconsul/releases

v0.6.0 downloads mostly have the zip file extension, but v0.5.0, v0.4.0 and v0.3.0 mostly use tar.gz. Before that the downloads have no extension. Will it be zip going forward or tar.gz? If tar.gz, can we update the v0.6.0 releases to include tar.gz downloads?

**Comment by sethvargo** [comment]
Hi @stevecrozz 

We moved all our releases to https://releases.hashicorp.com/. You can read more here: https://www.hashicorp.com/blog/hashicorp-and-fastly.html. We keep the old ones around so links aren't broken.

**Comment by stevecrozz** [comment]
Thanks @sethvargo. I've put in a PR #95 to update the README.md accordingly.
