### ISSUE TITLE
Use vault app-id/user-id to auth?

### ISSUE THREAD

**Issue by JoeOrtiz** [hashicorp/envconsul#96]
Can envconsul instead of using a vault-token to use app-id/user-id ?

I notice now if you use a token from app-id/user-id you can't use it with envconsul as it fails with:

"* lease not found or lease is not renewable"

**Comment by sethvargo** [comment]
Hi @JoeOrtiz 

Thank you for opening an issue. You can read a more detailed explanation [here](https://github.com/hashicorp/consul-template/issues/318#issuecomment-169731445), but I think the tools in the Vault ecosystem should not/cannot be responsible for (re)-implementing every supported authentication scheme provided by Vault. Unfortunately it's just not sustainable. Instead, I think there's room for a tool (perhaps or just Vault itself) which handles all these authentications and passes the token to the process.Thanks! :smile:
