### ISSUE TITLE
VAULT_TOKEN 

### ISSUE THREAD

**Issue by dkhunt27** [hashicorp/envconsul#97]
I am trying to wire up envconsult to use vault.  I have confirmed that the var VAULT_TOKEN is set/exported in the environment...however, not sure how to use it in the configuration file so I do not have to put the token directly in it.

Here is what I have tried

This works, putting the actual token in the config file

vault {
  ...
  token = "[ACTUAL TOKEN]"
  ...
}

The following does not work for me

token = "${VAULT_TOKEN}"

token = "$VAULT_TOKEN"

token = "VAULT_TOKEN"

and completely removing the token line in the config

How are you supposed to specify to use the env var VAULT_TOKEN in the config?

Thanks

**Comment by jippi** [comment]
@dkhunt27 omit it entirely, envconsul will read it from the real ENV if the ' VAULT_TOKEN` config key is omitted from the config file :)

**Comment by dkhunt27** [comment]
I tried that and it didn't work.  Just crawling through the code...I didn't see anywhere it was adding the VAULT_TOKEN to the config....I did see it for other env vars, but not VAULT_TOKEN...I could have missed it though.

I did find this in the config.go...but no VAULT_TOKEN handling

	if v := os.Getenv("CONSUL_HTTP_ADDR"); v != "" {
		config.Consul = v
	}

	if v := os.Getenv("CONSUL_TOKEN"); v != "" {
		config.Token = v
	}

	if v := os.Getenv("VAULT_ADDR"); v != "" {
		config.Vault.Address = v
	}

	if v := os.Getenv("VAULT_CAPATH"); v != "" {
		config.Vault.SSL.Cert = v
	}

	if v := os.Getenv("VAULT_CACERT"); v != "" {
		config.Vault.SSL.CaCert = v
	}

	if v := os.Getenv("VAULT_SKIP_VERIFY"); v != "" {
		config.Vault.SSL.Verify = false

**Comment by sethvargo** [comment]
Hi there,

I just verified this is working properly in the latest version of envconsul. The envvar is read in the client library: https://github.com/hashicorp/vault/blob/a26d992e9afb337ea4ff598c3fee4981d77f2337/api/client.go#L202-L204. Please make sure you are on the latest version.
