### ISSUE TITLE
add exec option to replace process with application

### ISSUE THREAD

**Issue by stevecrozz** [hashicorp/envconsul#98]
For my use case, I don't need or want envconsul to hang around in the process tree handling signals or watching for updates from consul. I would like an option for envconsul to run once, prepare the process environment, and then exec my application process using https://golang.org/pkg/syscall/#Exec.

I'm not particular about the name of the option, but -exec seems like a good choice.

Would a PR to add this option be welcome? Any other thoughts?

**Comment by sethvargo** [comment]
Hi @stevecrozz 

Thank you for opening an issue. I think this type of feature would defeat the purpose of envconsul a bit, since it's breaks the major API promise of "restarts the application when changes occur". What do you think?

**Comment by stevecrozz** [comment]
I can't speak to the purpose of envconsul, but the reason I use envconsul is for the simple way it allows me to fetch just what I need from consul and populate the process environment without persisting it to disk.

I prefer to manage my application starts and stops with other automation tools. We handle this in different ways, but there's often a need to start new processes with new inputs and once they are healthy, switch our load balancers to the new processes. Or sometimes we might want to do phased restarts where we leave some old processes running (with old inputs) while we take some time to bring in new processes with new inputs.

Using this proposed feature doesn't defeat the purpose I have in mind for envconsul, but using it definitely does defeat the purpose of having envconsul manage application restarts. My thought is that I'd like to opt-out of that part of envconsul, but I still value all the other stuff it does

**Comment by sethvargo** [comment]
Hi @stevecrozz 

You can use the `-once` flag to achieve most of the behavior you desire. This will only lookup changes during the initial process launch, but it won't watch Consul for changes. Any signal you send to envconsul is also sent to the child.

**Comment by stevecrozz** [comment]
I have seen the `-once` flag and it does almost what I want. But what is the point of continuing to run envconsul after its done its job when you pass the `-once` flag? When run with `-once` and after the initial run, it doesn't seem like envconsul can do anything helpful, so why not replace it with the application process?

I can't come up with a use case that would cause breakage because of the way this works, but it seems unnecessary to have the envconsul process continue to live after its done.

**Comment by sethvargo** [comment]
Hi @stevecrozz 

One of the advantages is that it behaves just like non-once mode :smile:. envconsul also listens for certain signals to reload config, which you wouldn't get if you replace the process. Just to play Devil's advocate - what is the advantage of replacing it entirely?

**Comment by stevecrozz** [comment]
My thought is it would be nice to (optionally) be able to ensure envconsul does its job 'once' and never does anything again. And the most straightforward way to provide that guarantee is to replace it. For my use case, I want to make 100% sure it can't do any kind of reloading.

In other words, I would like my app to be in complete control. That said, I will certainly understand if what I want isn't in line with the project goals.

**Comment by sethvargo** [comment]
Hi @stevecrozz 

I did some research here. Unfortunately there doesn't seem to be a way to do this that supports all operating systems. In particular, `syscall.Exec` just [returns an error on Windows](https://golang.org/src/syscall/exec_windows.go#L335) because Windows does not support exec. As such, we'd have differing behavior for our Windows binaries than our Linux/BSD binaries. The differing behaviors could cause confusion. Given that this is mostly achievable with the current `once` and other configuration parameters, I'm going to say "no" to this for now. We can definitely revisit this in the future if the use case becomes more prevalent, but I don't think the awards justify the tradeoffs at this time. Sorry! 😦

**Comment by stevecrozz** [comment]
I understand. Thanks for considering. It's not worth introducing if it makes for different windows/linux behavior.
