### ISSUE TITLE
Vault Token Auto Renewal Behavior

### ISSUE THREAD

**Issue by todoubled** [hashicorp/envconsul#99]
I’m a complete go newbie but I’ve been digging into the code a bit to understand the vault token auto renewal behavior. 

It seems as though when the token is set via `VAULT_TOKEN` environment variable instead of explicit HCL configuration, token renewal doesn’t happen because [`config.Vault.Token == “”`](https://github.com/hashicorp/envconsul/blob/ac60abcb17ffdab8c71c59d6219dc025b93c43c9/runner.go#L735). Am I reading that correctly? We’re not seeing tokens auto renewed in production currently when our tokens are set via environment variable.

I’d like to write a test to demonstrate this but I’m also having trouble getting this project running locally. Likely due to my go inexperience, but I’m seeing `src/github.com/hashicorp/consul/vendor/github.com/hashicorp/hil/ast/ast.go:44: running “stringer”: exec: “stringer”: executable file not found in $PATH` when I try to `make`.

Can you confirm/deny the renewal behavior I outlined above when `VAULT_TOKEN` is used instead of `vault.token` in configuration?  Also, are there any tips on getting past the error I mentioned so I can try to prove this out myself locally? Thanks for all the great hashicorp products!

**Comment by sethvargo** [comment]
Yea, I just confirmed this bug in Consul Template and [fixed it here](https://github.com/hashicorp/consul-template/commit/2431448c7edd50fd2a2165f4a709f0bb1736e0a3). Probably need a similar fix in envconsul
